obj-$(CONFIG_TEGRA_HDMI_MHL) += sii9234.o
obj-$(CONFIG_TEGRA_HDMI_MHL) += i2c_master_sw.o
#obj-$(CONFIG_TEGRA_HDMI_MHL) += si_cpCbus.o
obj-$(CONFIG_TEGRA_HDMI_MHL) += TPI.o
obj-$(CONFIG_TEGRA_HDMI_MHL) += TPI_Access.o
obj-$(CONFIG_TEGRA_HDMI_MHL) += Util.o
obj-$(CONFIG_TEGRA_HDMI_MHL) += sii_mhltx.o
obj-$(CONFIG_TEGRA_HDMI_MHL) += mhltx_rcptable.o

