/**************************************************
 *   WARNING  WARNING  WARNING  WARNING  WARNING
 *
 *   this file is only for configuring GPIO that is
 *      * unused, or
 *      * no owner
 *   , rest GPIO should be setup on elsewhere
 *
 *   WARNING  WARNING  WARNING  WARNING  WARNING
 **************************************************/

#include "htc-gpio.h"

#include <linux/init.h>
#include <linux/irq.h>
#include <linux/interrupt.h>
#include <linux/delay.h>
#include <linux/err.h>
#include <linux/suspend.h>

#include <linux/io.h>
#include <linux/gpio.h>

#include <mach/iomap.h>
#include <mach/pinmux.h>
#include <mach/board_htc.h>

#include "gpio-names.h"
#include "htc-gpio.h"
#include "board.h"

#define DEBUG_ENTRY() \
    pr_debug("[htc-gpio] entering %s\n", __func__)

extern const int gpio_to_pingroup[TEGRA_MAX_GPIO];

#define GPIO_SETUP(_gpio, _state) \
	__gpio_setup(TEGRA_GPIO_P ## _gpio, GPIO_SETUP_ ## _state);

#define GPIO_CONFIG_MAP(gpio, value) \
    [TEGRA_GPIO_P ## gpio] = # value

const char* enr_td_suspend_gpio_config_xc[TEGRA_NR_GPIOS]= {
	GPIO_CONFIG_MAP(A0, O(L)),
	GPIO_CONFIG_MAP(A1, A),
	GPIO_CONFIG_MAP(A2, O(L)),
	GPIO_CONFIG_MAP(A3, O(L)),
	GPIO_CONFIG_MAP(A4, O(L)),
	GPIO_CONFIG_MAP(A5, O(L)),
	GPIO_CONFIG_MAP(A6, A),
	GPIO_CONFIG_MAP(A7, A(PU)),
	GPIO_CONFIG_MAP(B0, A),
	GPIO_CONFIG_MAP(B1, A),
	GPIO_CONFIG_MAP(B2, O(H)),
	GPIO_CONFIG_MAP(B3, O(L)),
	GPIO_CONFIG_MAP(B4, A(PU)),
	GPIO_CONFIG_MAP(B5, A(PU)),
	GPIO_CONFIG_MAP(B6, A(PU)),
	GPIO_CONFIG_MAP(B7, A(PU)),
	GPIO_CONFIG_MAP(C0, O(H)),
	GPIO_CONFIG_MAP(C1, O(L)),
	GPIO_CONFIG_MAP(C2, O(L)),
	GPIO_CONFIG_MAP(C3, O(L)),
	GPIO_CONFIG_MAP(C4, A),
	GPIO_CONFIG_MAP(C5, A),
	GPIO_CONFIG_MAP(C6, O(H)),
	GPIO_CONFIG_MAP(C7, I(PU)),
	GPIO_CONFIG_MAP(D0, O(L)),
	GPIO_CONFIG_MAP(D1, O(L)),
	GPIO_CONFIG_MAP(D2, O(L)),
	GPIO_CONFIG_MAP(D3, O(L)),
	GPIO_CONFIG_MAP(D4, O(L)),
	GPIO_CONFIG_MAP(D5, O(L)),
	GPIO_CONFIG_MAP(D6, O(L)),
	GPIO_CONFIG_MAP(D7, O(L)),
	GPIO_CONFIG_MAP(E0, O(L)),
	GPIO_CONFIG_MAP(E1, O(L)),
	GPIO_CONFIG_MAP(E2, O(L)),
	GPIO_CONFIG_MAP(E3, O(L)),
	GPIO_CONFIG_MAP(E4, O(L)),
	GPIO_CONFIG_MAP(E5, O(L)),
	GPIO_CONFIG_MAP(E6, O(L)),
	GPIO_CONFIG_MAP(E7, O(L)),
	GPIO_CONFIG_MAP(F0, O(L)),
	GPIO_CONFIG_MAP(F1, O(L)),
	GPIO_CONFIG_MAP(F2, O(L)),
	GPIO_CONFIG_MAP(F3, O(H)),
	GPIO_CONFIG_MAP(F4, O(L)),
	GPIO_CONFIG_MAP(F5, O(L)),
	GPIO_CONFIG_MAP(F6, O(L)),
	GPIO_CONFIG_MAP(F7, O(L)),
	GPIO_CONFIG_MAP(G0, I(NP)),
	GPIO_CONFIG_MAP(G1, I(NP)),
	GPIO_CONFIG_MAP(G2, I(NP)),
	GPIO_CONFIG_MAP(G3, I(NP)),
	GPIO_CONFIG_MAP(G4, I(NP)),
	GPIO_CONFIG_MAP(G5, I(NP)),
	GPIO_CONFIG_MAP(G6, I(NP)),
	GPIO_CONFIG_MAP(G7, I(NP)),
	GPIO_CONFIG_MAP(H0, O(L)),
	GPIO_CONFIG_MAP(H1, O(L)),
	GPIO_CONFIG_MAP(H2, O(L)),
	GPIO_CONFIG_MAP(H3, I(NP)),
	GPIO_CONFIG_MAP(H4, O(L)),
	GPIO_CONFIG_MAP(H5, O(L)),
	GPIO_CONFIG_MAP(H6, O(L)),
	GPIO_CONFIG_MAP(H7, O(L)),
	GPIO_CONFIG_MAP(I0, I(NP)),
	GPIO_CONFIG_MAP(I1, I(NP)),
	GPIO_CONFIG_MAP(I2, O(L)),
	GPIO_CONFIG_MAP(I3, O(L)),
	GPIO_CONFIG_MAP(I4, O(L)),
	GPIO_CONFIG_MAP(I5, I(NP)),
	GPIO_CONFIG_MAP(I6, I(NP)),
	GPIO_CONFIG_MAP(I7, O(L)),
	GPIO_CONFIG_MAP(J0, I(NP)),
	GPIO_CONFIG_MAP(J1, I(NP)),
	GPIO_CONFIG_MAP(J2, I(NP)),
	GPIO_CONFIG_MAP(J3, I(PD)),
	GPIO_CONFIG_MAP(J4, O(L)),
	GPIO_CONFIG_MAP(J5, O(L)),
	GPIO_CONFIG_MAP(J6, O(L)),
	GPIO_CONFIG_MAP(J7, A),
	GPIO_CONFIG_MAP(K0, I(NP)),
	GPIO_CONFIG_MAP(K1, I(NP)),
	GPIO_CONFIG_MAP(K2, I(PU)),
	GPIO_CONFIG_MAP(K3, O(L)),
	GPIO_CONFIG_MAP(K4, O(L)),
	GPIO_CONFIG_MAP(K5, O(L)),
	GPIO_CONFIG_MAP(K6, O(L)),
	GPIO_CONFIG_MAP(K7, O(L)),
	GPIO_CONFIG_MAP(L0, O(L)),
	GPIO_CONFIG_MAP(L1, O(L)),
	GPIO_CONFIG_MAP(L2, O(L)),
	GPIO_CONFIG_MAP(L3, O(L)),
	GPIO_CONFIG_MAP(L4, O(L)),
	GPIO_CONFIG_MAP(L5, O(L)),
	GPIO_CONFIG_MAP(L6, O(L)),
	GPIO_CONFIG_MAP(L7, O(L)),
	GPIO_CONFIG_MAP(M0, I(NP)),
	GPIO_CONFIG_MAP(M1, I(NP)),
	GPIO_CONFIG_MAP(M2, O(L)),
	GPIO_CONFIG_MAP(M3, O(L)),
	GPIO_CONFIG_MAP(M4, O(H)),
	GPIO_CONFIG_MAP(M5, O(H)),
	GPIO_CONFIG_MAP(M6, O(L)),
	GPIO_CONFIG_MAP(M7, O(L)),
	GPIO_CONFIG_MAP(N0, O(H)),
	GPIO_CONFIG_MAP(N1, O(L)),
	GPIO_CONFIG_MAP(N2, I(PU)),
	GPIO_CONFIG_MAP(N3, O(L)),
	GPIO_CONFIG_MAP(N4, O(L)),
	GPIO_CONFIG_MAP(N5, I(NP)),
	GPIO_CONFIG_MAP(N6, O(L)),
	GPIO_CONFIG_MAP(N7, I(NP)),
	GPIO_CONFIG_MAP(O0, O(L)),
	GPIO_CONFIG_MAP(O1, A),
	GPIO_CONFIG_MAP(O2, A),
	GPIO_CONFIG_MAP(O3, O(L)),
	GPIO_CONFIG_MAP(O4, I(NP)),
	GPIO_CONFIG_MAP(O5, I(PU)),
	GPIO_CONFIG_MAP(O6, O(L)),
	GPIO_CONFIG_MAP(O7, O(L)),
	GPIO_CONFIG_MAP(P0, O(L)),
	GPIO_CONFIG_MAP(P1, O(L)),
	GPIO_CONFIG_MAP(P2, O(L)),
	GPIO_CONFIG_MAP(P3, O(L)),
	GPIO_CONFIG_MAP(P4, O(L)),
	GPIO_CONFIG_MAP(P5, O(L)),
	GPIO_CONFIG_MAP(P6, O(L)),
	GPIO_CONFIG_MAP(P7, O(H)),
	GPIO_CONFIG_MAP(Q0, O(L)),
	GPIO_CONFIG_MAP(Q1, O(L)),
	GPIO_CONFIG_MAP(Q2, O(L)),
	GPIO_CONFIG_MAP(Q3, O(L)),
	GPIO_CONFIG_MAP(Q4, O(L)),
	GPIO_CONFIG_MAP(Q5, O(L)),
	GPIO_CONFIG_MAP(Q6, O(L)),
	GPIO_CONFIG_MAP(Q7, O(L)),
	GPIO_CONFIG_MAP(R0, I(NP)),
	GPIO_CONFIG_MAP(R1, O(L)),
	GPIO_CONFIG_MAP(R2, O(H)),
	GPIO_CONFIG_MAP(R3, O(L)),
	GPIO_CONFIG_MAP(R4, O(L)),
	GPIO_CONFIG_MAP(R5, O(L)),
	GPIO_CONFIG_MAP(R6, I(NP)), //
	GPIO_CONFIG_MAP(R7, I(NP)), //
	GPIO_CONFIG_MAP(S0, I(PU)),
	GPIO_CONFIG_MAP(S1, O(L)),
	GPIO_CONFIG_MAP(S2, I(NP)),
	GPIO_CONFIG_MAP(S3, O(L)),
	GPIO_CONFIG_MAP(S4, O(L)),
	GPIO_CONFIG_MAP(S5, O(L)),
	GPIO_CONFIG_MAP(S6, O(L)),
	GPIO_CONFIG_MAP(S7, O(L)),
	GPIO_CONFIG_MAP(T0, O(L)),
	GPIO_CONFIG_MAP(T1, O(L)),
	GPIO_CONFIG_MAP(T2, O(L)),
	GPIO_CONFIG_MAP(T3, O(L)),
	GPIO_CONFIG_MAP(T4, O(L)),
	GPIO_CONFIG_MAP(T5, A),
	GPIO_CONFIG_MAP(T6, A),
	GPIO_CONFIG_MAP(T7, A(PU)),
	GPIO_CONFIG_MAP(U0, O(H)),
	GPIO_CONFIG_MAP(U1, O(H)),
	GPIO_CONFIG_MAP(U2, I(NP)),
	GPIO_CONFIG_MAP(U3, O(H)),
	GPIO_CONFIG_MAP(U4, I(NP)),
	GPIO_CONFIG_MAP(U5, I(NP)),
	GPIO_CONFIG_MAP(U6, I(PU)),
	GPIO_CONFIG_MAP(U7, O(L)),
	GPIO_CONFIG_MAP(V0, I(NP)),
	GPIO_CONFIG_MAP(V1, I(NP)),
	GPIO_CONFIG_MAP(V2, O(H)),
	GPIO_CONFIG_MAP(V3, O(L)),
	GPIO_CONFIG_MAP(V4, A),
	GPIO_CONFIG_MAP(V5, A),
	GPIO_CONFIG_MAP(V6, I(PU)),
	GPIO_CONFIG_MAP(V7, O(L)),
	GPIO_CONFIG_MAP(W0, I(PU)),
	GPIO_CONFIG_MAP(W1, O(L)),
	GPIO_CONFIG_MAP(W2, I(PU)),
	GPIO_CONFIG_MAP(W3, I(PU)),
	GPIO_CONFIG_MAP(W4, O(L)),
	GPIO_CONFIG_MAP(W5, O(H)),
	GPIO_CONFIG_MAP(W6, A),
	GPIO_CONFIG_MAP(W7, A),
	GPIO_CONFIG_MAP(X0, A),
	GPIO_CONFIG_MAP(X1, A),
	GPIO_CONFIG_MAP(X2, A),
	GPIO_CONFIG_MAP(X3, A),
	GPIO_CONFIG_MAP(X4, O(L)),
	GPIO_CONFIG_MAP(X5, I(PU)),
	GPIO_CONFIG_MAP(X6, O(L)),
	GPIO_CONFIG_MAP(X7, O(L)),
	GPIO_CONFIG_MAP(Y0, O(H)),
	GPIO_CONFIG_MAP(Y1, O(L)),
	GPIO_CONFIG_MAP(Y2, O(L)),
	GPIO_CONFIG_MAP(Y3, O(H)),
	GPIO_CONFIG_MAP(Y4, O(L)),
	GPIO_CONFIG_MAP(Y5, I(PU)), 
	GPIO_CONFIG_MAP(Y6, I(NP)),
	GPIO_CONFIG_MAP(Y7, O(L)),
	GPIO_CONFIG_MAP(Z0, O(H)),
	GPIO_CONFIG_MAP(Z1, O(L)),
	GPIO_CONFIG_MAP(Z2, O(H)),
	GPIO_CONFIG_MAP(Z3, O(L)),
	GPIO_CONFIG_MAP(Z4, O(L)),
	GPIO_CONFIG_MAP(Z5, O(L)),
	GPIO_CONFIG_MAP(Z6, A),
	GPIO_CONFIG_MAP(Z7, A),
	GPIO_CONFIG_MAP(AA0, A(PU)),
	GPIO_CONFIG_MAP(AA1, A(PU)),
	GPIO_CONFIG_MAP(AA2, A(PU)),
	GPIO_CONFIG_MAP(AA3, A(PU)),
	GPIO_CONFIG_MAP(AA4, A(PU)),
	GPIO_CONFIG_MAP(AA5, A(PU)),
	GPIO_CONFIG_MAP(AA6, A(PU)),
	GPIO_CONFIG_MAP(AA7, A(PU)),
	GPIO_CONFIG_MAP(BB0, O(L)),
	GPIO_CONFIG_MAP(BB1, O(L)),
	GPIO_CONFIG_MAP(BB2, O(L)),
	GPIO_CONFIG_MAP(BB3, O(L)),
	GPIO_CONFIG_MAP(BB4, O(L)),
	GPIO_CONFIG_MAP(BB5, O(L)),
	GPIO_CONFIG_MAP(BB6, I(NP)),
	GPIO_CONFIG_MAP(BB7, O(L)),
	GPIO_CONFIG_MAP(CC0, O(L)),
	GPIO_CONFIG_MAP(CC1, O(L)),
	GPIO_CONFIG_MAP(CC2, I(PU)),
	GPIO_CONFIG_MAP(CC3, A),
	GPIO_CONFIG_MAP(CC4, O(L)),
	GPIO_CONFIG_MAP(CC5, O(H)),
	GPIO_CONFIG_MAP(CC6, O(L)),
	GPIO_CONFIG_MAP(CC7, O(L)),
	GPIO_CONFIG_MAP(DD0, O(L)),
	GPIO_CONFIG_MAP(DD1, O(L)),
	GPIO_CONFIG_MAP(DD2, O(L)),
	GPIO_CONFIG_MAP(DD3, O(L)),
	GPIO_CONFIG_MAP(DD4, O(L)),
	GPIO_CONFIG_MAP(DD5, O(L)),
	GPIO_CONFIG_MAP(DD6, O(L)),
	GPIO_CONFIG_MAP(DD7, O(L)),
	GPIO_CONFIG_MAP(EE0, O(L)),
	GPIO_CONFIG_MAP(EE1, I(NP)),
	GPIO_CONFIG_MAP(EE2, O(L)),
	GPIO_CONFIG_MAP(EE3, O(L)),

};


const char* quo_suspend_gpio_config_xa[TEGRA_NR_GPIOS]= {
	GPIO_CONFIG_MAP(A0, O(L)),
	GPIO_CONFIG_MAP(A1, I(PU)),
	GPIO_CONFIG_MAP(A2, A),
	GPIO_CONFIG_MAP(A3, A),
	GPIO_CONFIG_MAP(A4, A),
	GPIO_CONFIG_MAP(A5, A),
	GPIO_CONFIG_MAP(A6, A),
	GPIO_CONFIG_MAP(A7, A),
	GPIO_CONFIG_MAP(B0, O(L)),
	GPIO_CONFIG_MAP(B1, O(L)),
	GPIO_CONFIG_MAP(B2, O(L)),
	GPIO_CONFIG_MAP(B3, O(L)),
	GPIO_CONFIG_MAP(B4, A),
	GPIO_CONFIG_MAP(B5, A),
	GPIO_CONFIG_MAP(B6, A),
	GPIO_CONFIG_MAP(B7, A),
	GPIO_CONFIG_MAP(C0, O(H)),
	GPIO_CONFIG_MAP(C1, O(L)),
	GPIO_CONFIG_MAP(C2, O(L)),
	GPIO_CONFIG_MAP(C3, O(L)),
	GPIO_CONFIG_MAP(C4, A),
	GPIO_CONFIG_MAP(C5, A),
	GPIO_CONFIG_MAP(C6, O(L)),
	GPIO_CONFIG_MAP(C7, I(PU)),
	GPIO_CONFIG_MAP(D0, I(NP)),
	GPIO_CONFIG_MAP(D1, I(PU)),
	GPIO_CONFIG_MAP(D2, O(L)),
	GPIO_CONFIG_MAP(D3, I(NP)),
	GPIO_CONFIG_MAP(D4, O(L)),
	GPIO_CONFIG_MAP(D5, O(L)),
	GPIO_CONFIG_MAP(D6, O(L)),
	GPIO_CONFIG_MAP(D7, O(L)),
	GPIO_CONFIG_MAP(E0, O(L)),
	GPIO_CONFIG_MAP(E1, O(L)),
	GPIO_CONFIG_MAP(E2, O(L)),
	GPIO_CONFIG_MAP(E3, O(L)),
	GPIO_CONFIG_MAP(E4, O(L)),
	GPIO_CONFIG_MAP(E5, O(L)),
	GPIO_CONFIG_MAP(E6, O(L)),
	GPIO_CONFIG_MAP(E7, O(L)),
	GPIO_CONFIG_MAP(F0, O(L)),
	GPIO_CONFIG_MAP(F1, O(L)),
	GPIO_CONFIG_MAP(F2, O(L)),
	GPIO_CONFIG_MAP(F3, O(L)),
	GPIO_CONFIG_MAP(F4, O(L)),
	GPIO_CONFIG_MAP(F5, O(L)),
	GPIO_CONFIG_MAP(F6, O(L)),
	GPIO_CONFIG_MAP(F7, O(L)),
	GPIO_CONFIG_MAP(G0, I(NP)),
	GPIO_CONFIG_MAP(G1, I(NP)),
	GPIO_CONFIG_MAP(G2, I(NP)),
	GPIO_CONFIG_MAP(G3, I(NP)),
	GPIO_CONFIG_MAP(G4, I(NP)),
	GPIO_CONFIG_MAP(G5, I(NP)),
	GPIO_CONFIG_MAP(G6, I(NP)),
	GPIO_CONFIG_MAP(G7, I(NP)),
	GPIO_CONFIG_MAP(H0, O(L)),
	GPIO_CONFIG_MAP(H1, O(L)),
	GPIO_CONFIG_MAP(H2, O(L)),
	GPIO_CONFIG_MAP(H3, I(NP)),
	GPIO_CONFIG_MAP(H4, O(L)),
	GPIO_CONFIG_MAP(H5, I(PU)),
	GPIO_CONFIG_MAP(H6, I(PU)),
	GPIO_CONFIG_MAP(H7, O(H)),
	GPIO_CONFIG_MAP(I0, I(NP)),
	GPIO_CONFIG_MAP(I1, I(NP)),
	GPIO_CONFIG_MAP(I2, O(L)),
	GPIO_CONFIG_MAP(I3, O(L)),
	GPIO_CONFIG_MAP(I4, O(L)),
	GPIO_CONFIG_MAP(I5, I(PU)),
	GPIO_CONFIG_MAP(I6, I(PD)),
	GPIO_CONFIG_MAP(I7, O(L)),
	GPIO_CONFIG_MAP(J0, I(NP)),
	GPIO_CONFIG_MAP(J1, O(L)),
	GPIO_CONFIG_MAP(J2, I(PD)),
	GPIO_CONFIG_MAP(J3, O(L)),
	GPIO_CONFIG_MAP(J4, O(L)),
	GPIO_CONFIG_MAP(J5, I(PD)),
	GPIO_CONFIG_MAP(J6, O(L)),
	GPIO_CONFIG_MAP(J7, O(L)),
	GPIO_CONFIG_MAP(K0, I(NP)),
	GPIO_CONFIG_MAP(K1, I(NP)),
	GPIO_CONFIG_MAP(K2, O(L)),
	GPIO_CONFIG_MAP(K3, O(L)),
	GPIO_CONFIG_MAP(K4, O(L)),
	GPIO_CONFIG_MAP(K5, O(L)),
	GPIO_CONFIG_MAP(K6, O(L)),
	GPIO_CONFIG_MAP(K7, O(L)),
	GPIO_CONFIG_MAP(L0, O(L)),
	GPIO_CONFIG_MAP(L1, O(L)),
	GPIO_CONFIG_MAP(L2, O(L)),
	GPIO_CONFIG_MAP(L3, O(L)),
	GPIO_CONFIG_MAP(L4, O(L)),
	GPIO_CONFIG_MAP(L5, O(L)),
	GPIO_CONFIG_MAP(L6, O(L)),
	GPIO_CONFIG_MAP(L7, O(L)),
	GPIO_CONFIG_MAP(M0, O(L)),
	GPIO_CONFIG_MAP(M1, O(L)),
	GPIO_CONFIG_MAP(M2, O(L)),
	GPIO_CONFIG_MAP(M3, O(L)),
	GPIO_CONFIG_MAP(M4, O(L)),
	GPIO_CONFIG_MAP(M5, O(L)),
	GPIO_CONFIG_MAP(M6, O(L)),
	GPIO_CONFIG_MAP(M7, O(L)),
	GPIO_CONFIG_MAP(N0, O(L)),
	GPIO_CONFIG_MAP(N1, O(L)),
	GPIO_CONFIG_MAP(N2, O(L)),
	GPIO_CONFIG_MAP(N3, O(L)),
	GPIO_CONFIG_MAP(N4, O(L)),
	GPIO_CONFIG_MAP(N5, O(L)),
	GPIO_CONFIG_MAP(N6, O(L)),
	GPIO_CONFIG_MAP(N7, I(PD)),
	GPIO_CONFIG_MAP(O0, O(H)),
	GPIO_CONFIG_MAP(O1, A),
	GPIO_CONFIG_MAP(O2, A),
	GPIO_CONFIG_MAP(O3, O(L)),
	GPIO_CONFIG_MAP(O4, O(L)),
	GPIO_CONFIG_MAP(O5, O(L)),
	GPIO_CONFIG_MAP(O6, O(L)),
	GPIO_CONFIG_MAP(O7, I(NP)),
	GPIO_CONFIG_MAP(P0, O(H)),
	GPIO_CONFIG_MAP(P1, O(L)),
	GPIO_CONFIG_MAP(P2, I(NP)),
	GPIO_CONFIG_MAP(P3, O(L)),
	GPIO_CONFIG_MAP(P4, O(L)),
	GPIO_CONFIG_MAP(P5, O(L)),
	GPIO_CONFIG_MAP(P6, O(L)),
	GPIO_CONFIG_MAP(P7, O(L)),
	GPIO_CONFIG_MAP(Q0, O(L)),
	GPIO_CONFIG_MAP(Q1, O(L)),
	GPIO_CONFIG_MAP(Q2, O(L)),
	GPIO_CONFIG_MAP(Q3, O(L)),
	GPIO_CONFIG_MAP(Q4, O(L)),
	GPIO_CONFIG_MAP(Q5, O(L)),
	GPIO_CONFIG_MAP(Q6, O(L)),
	GPIO_CONFIG_MAP(Q7, O(L)),
	GPIO_CONFIG_MAP(R0, I(PU)),
	GPIO_CONFIG_MAP(R1, O(L)),
	GPIO_CONFIG_MAP(R2, O(H)),
	GPIO_CONFIG_MAP(R3, O(L)),
	GPIO_CONFIG_MAP(R4, O(H)),
	GPIO_CONFIG_MAP(R5, O(L)),
	GPIO_CONFIG_MAP(R6, O(L)),
	GPIO_CONFIG_MAP(R7, O(L)),
	GPIO_CONFIG_MAP(S0, I(PU)),
	GPIO_CONFIG_MAP(S1, O(L)),
	GPIO_CONFIG_MAP(S2, I(PD)),
	GPIO_CONFIG_MAP(S3, O(L)),
	GPIO_CONFIG_MAP(S4, O(L)),
	GPIO_CONFIG_MAP(S5, O(L)),
	GPIO_CONFIG_MAP(S6, O(L)),
	GPIO_CONFIG_MAP(S7, O(L)),
	GPIO_CONFIG_MAP(T0, O(L)),
	GPIO_CONFIG_MAP(T1, O(L)),
	GPIO_CONFIG_MAP(T2, O(L)),
	GPIO_CONFIG_MAP(T3, O(L)),
	GPIO_CONFIG_MAP(T4, O(L)),
	GPIO_CONFIG_MAP(T5, A),
	GPIO_CONFIG_MAP(T6, A),
	GPIO_CONFIG_MAP(T7, A),
	GPIO_CONFIG_MAP(U0, O(L)),
	GPIO_CONFIG_MAP(U1, O(L)),
	GPIO_CONFIG_MAP(U2, O(L)),
	GPIO_CONFIG_MAP(U3, O(L)),
	GPIO_CONFIG_MAP(U4, O(L)),
	GPIO_CONFIG_MAP(U5, I(NP)),
	GPIO_CONFIG_MAP(U6, I(NP)),
	GPIO_CONFIG_MAP(U7, O(L)),
	GPIO_CONFIG_MAP(V0, I(PU)),
	GPIO_CONFIG_MAP(V1, O(L)),
	GPIO_CONFIG_MAP(V2, O(L)),
	GPIO_CONFIG_MAP(V3, O(L)),
	GPIO_CONFIG_MAP(V4, O(L)),
	GPIO_CONFIG_MAP(V5, O(L)),
	GPIO_CONFIG_MAP(V6, O(L)),
	GPIO_CONFIG_MAP(V7, O(L)),
	GPIO_CONFIG_MAP(W0, O(L)),
	GPIO_CONFIG_MAP(W1, O(L)),
	GPIO_CONFIG_MAP(W2, I(PU)),
	GPIO_CONFIG_MAP(W3, I(PU)),
	GPIO_CONFIG_MAP(W4, O(L)),
	GPIO_CONFIG_MAP(W5, O(L)),
	GPIO_CONFIG_MAP(W6, A),
	GPIO_CONFIG_MAP(W7, A),
	GPIO_CONFIG_MAP(X0, A),
	GPIO_CONFIG_MAP(X1, A),
	GPIO_CONFIG_MAP(X2, A),
	GPIO_CONFIG_MAP(X3, A),
	GPIO_CONFIG_MAP(X4, O(L)),
	GPIO_CONFIG_MAP(X5, O(L)),
	GPIO_CONFIG_MAP(X6, O(L)),
	GPIO_CONFIG_MAP(X7, O(L)),
	GPIO_CONFIG_MAP(Y0, O(L)),
	GPIO_CONFIG_MAP(Y1, O(L)),
	GPIO_CONFIG_MAP(Y2, O(L)),
	GPIO_CONFIG_MAP(Y3, O(L)),
	GPIO_CONFIG_MAP(Y4, O(L)),
	GPIO_CONFIG_MAP(Y5, O(L)),
	GPIO_CONFIG_MAP(Y6, O(L)),
	GPIO_CONFIG_MAP(Y7, O(L)),
	GPIO_CONFIG_MAP(Z0, O(L)),
	GPIO_CONFIG_MAP(Z1, O(L)),
	GPIO_CONFIG_MAP(Z2, O(L)),
	GPIO_CONFIG_MAP(Z3, O(L)),
	GPIO_CONFIG_MAP(Z4, O(L)),
	GPIO_CONFIG_MAP(Z5, O(L)),
	GPIO_CONFIG_MAP(Z6, A),
	GPIO_CONFIG_MAP(Z7, A),
	GPIO_CONFIG_MAP(AA0, A),
	GPIO_CONFIG_MAP(AA1, A),
	GPIO_CONFIG_MAP(AA2, A),
	GPIO_CONFIG_MAP(AA3, A),
	GPIO_CONFIG_MAP(AA4, A),
	GPIO_CONFIG_MAP(AA5, A),
	GPIO_CONFIG_MAP(AA6, A),
	GPIO_CONFIG_MAP(AA7, A),
	GPIO_CONFIG_MAP(BB0, O(L)),
	GPIO_CONFIG_MAP(BB1, O(L)),
	GPIO_CONFIG_MAP(BB2, O(L)),
	GPIO_CONFIG_MAP(BB3, O(L)),
	GPIO_CONFIG_MAP(BB4, O(L)),
	GPIO_CONFIG_MAP(BB5, O(L)),
	GPIO_CONFIG_MAP(BB6, O(L)),
	GPIO_CONFIG_MAP(BB7, O(L)),
	GPIO_CONFIG_MAP(CC0, O(L)),
	GPIO_CONFIG_MAP(CC1, O(L)),
	GPIO_CONFIG_MAP(CC2, I(PU)),
	GPIO_CONFIG_MAP(CC3, O(H)),
	GPIO_CONFIG_MAP(CC4, A),
	GPIO_CONFIG_MAP(CC5, O(L)),
	GPIO_CONFIG_MAP(CC6, O(L)),
	GPIO_CONFIG_MAP(CC7, O(L)),
	GPIO_CONFIG_MAP(DD0, O(L)),
	GPIO_CONFIG_MAP(DD1, O(L)),
	GPIO_CONFIG_MAP(DD2, O(L)),
	GPIO_CONFIG_MAP(DD3, O(L)),
	GPIO_CONFIG_MAP(DD4, O(L)),
	GPIO_CONFIG_MAP(DD5, O(L)),
	GPIO_CONFIG_MAP(DD6, O(L)),
	GPIO_CONFIG_MAP(DD7, O(L)),
	GPIO_CONFIG_MAP(EE0, O(L)),
	GPIO_CONFIG_MAP(EE1, O(L)),
	GPIO_CONFIG_MAP(EE2, O(L)),
	GPIO_CONFIG_MAP(EE3, O(L)),
};

const char* quo_suspend_gpio_config_xb[TEGRA_NR_GPIOS]= {
	GPIO_CONFIG_MAP(A0, SKIP),  //*
	GPIO_CONFIG_MAP(A1, I(PU)),
	GPIO_CONFIG_MAP(A2, A),
	GPIO_CONFIG_MAP(A3, A),
	GPIO_CONFIG_MAP(A4, A),
	GPIO_CONFIG_MAP(A5, A),
	GPIO_CONFIG_MAP(A6, O(L)),		//*
	GPIO_CONFIG_MAP(A7, O(L)),		//*
	GPIO_CONFIG_MAP(B0, SKIP),		//*
	GPIO_CONFIG_MAP(B1, SKIP),		//*
	GPIO_CONFIG_MAP(B2, O(L)),
	GPIO_CONFIG_MAP(B3, O(L)),
	GPIO_CONFIG_MAP(B4, O(L)),		//*
	GPIO_CONFIG_MAP(B5, O(L)),		//*
	GPIO_CONFIG_MAP(B6, O(L)),		//*
	GPIO_CONFIG_MAP(B7, O(L)),		//*
	GPIO_CONFIG_MAP(C0, O(H)),
	GPIO_CONFIG_MAP(C1, O(L)),
	GPIO_CONFIG_MAP(C2, O(L)),
	GPIO_CONFIG_MAP(C3, I(PD)),		//*
	GPIO_CONFIG_MAP(C4, A),
	GPIO_CONFIG_MAP(C5, A),
	GPIO_CONFIG_MAP(C6, O(L)),
	GPIO_CONFIG_MAP(C7, I(NP)),		//*
	GPIO_CONFIG_MAP(D0, I(NP)),
	GPIO_CONFIG_MAP(D1, O(H)),
	GPIO_CONFIG_MAP(D2, O(L)),
	GPIO_CONFIG_MAP(D3, I(PU)),		//*
	GPIO_CONFIG_MAP(D4, O(L)),
	GPIO_CONFIG_MAP(D5, O(L)),
	GPIO_CONFIG_MAP(D6, O(L)),
	GPIO_CONFIG_MAP(D7, O(L)),
	GPIO_CONFIG_MAP(E0, O(L)),
	GPIO_CONFIG_MAP(E1, O(L)),
	GPIO_CONFIG_MAP(E2, O(L)),
	GPIO_CONFIG_MAP(E3, O(L)),
	GPIO_CONFIG_MAP(E4, O(L)),
	GPIO_CONFIG_MAP(E5, O(L)),
	GPIO_CONFIG_MAP(E6, O(L)),
	GPIO_CONFIG_MAP(E7, O(L)),
	GPIO_CONFIG_MAP(F0, O(L)),
	GPIO_CONFIG_MAP(F1, O(L)),
	GPIO_CONFIG_MAP(F2, O(L)),
	GPIO_CONFIG_MAP(F3, O(L)),
	GPIO_CONFIG_MAP(F4, O(L)),
	GPIO_CONFIG_MAP(F5, O(L)),
	GPIO_CONFIG_MAP(F6, O(L)),
	GPIO_CONFIG_MAP(F7, O(L)),
	GPIO_CONFIG_MAP(G0, I(NP)),
	GPIO_CONFIG_MAP(G1, I(NP)),
	GPIO_CONFIG_MAP(G2, I(NP)),
	GPIO_CONFIG_MAP(G3, I(NP)),
	GPIO_CONFIG_MAP(G4, I(NP)),
	GPIO_CONFIG_MAP(G5, I(NP)),
	GPIO_CONFIG_MAP(G6, I(NP)),
	GPIO_CONFIG_MAP(G7, I(NP)),
	GPIO_CONFIG_MAP(H0, O(L)),
	GPIO_CONFIG_MAP(H1, O(L)),
	GPIO_CONFIG_MAP(H2, O(L)),
	GPIO_CONFIG_MAP(H3, I(NP)),
	GPIO_CONFIG_MAP(H4, O(L)),
	GPIO_CONFIG_MAP(H5, I(NP)),		//*
	GPIO_CONFIG_MAP(H6, I(PU)),
	GPIO_CONFIG_MAP(H7, O(H)),
	GPIO_CONFIG_MAP(I0, I(NP)),
	GPIO_CONFIG_MAP(I1, I(NP)),
	GPIO_CONFIG_MAP(I2, O(L)),
	GPIO_CONFIG_MAP(I3, I(PU)),
	GPIO_CONFIG_MAP(I4, O(L)),
	GPIO_CONFIG_MAP(I5, I(PU)),
	GPIO_CONFIG_MAP(I6, I(PD)),
	GPIO_CONFIG_MAP(I7, O(H)),
	GPIO_CONFIG_MAP(J0, I(NP)),
	GPIO_CONFIG_MAP(J1, O(L)),
	GPIO_CONFIG_MAP(J2, I(PD)),
	GPIO_CONFIG_MAP(J3, O(L)),
	GPIO_CONFIG_MAP(J4, O(L)),
	GPIO_CONFIG_MAP(J5, I(PD)),
	GPIO_CONFIG_MAP(J6, O(L)),
	GPIO_CONFIG_MAP(J7, O(L)),
	GPIO_CONFIG_MAP(K0, I(NP)),
	GPIO_CONFIG_MAP(K1, I(NP)),
	GPIO_CONFIG_MAP(K2, O(L)),
	GPIO_CONFIG_MAP(K3, O(L)),
	GPIO_CONFIG_MAP(K4, O(L)),
	GPIO_CONFIG_MAP(K5, SKIP),		//*
	GPIO_CONFIG_MAP(K6, O(L)),
	GPIO_CONFIG_MAP(K7, O(L)),
	GPIO_CONFIG_MAP(L0, O(L)),
	GPIO_CONFIG_MAP(L1, O(L)),
	GPIO_CONFIG_MAP(L2, O(L)),
	GPIO_CONFIG_MAP(L3, O(L)),
	GPIO_CONFIG_MAP(L4, O(L)),
	GPIO_CONFIG_MAP(L5, O(L)),
	GPIO_CONFIG_MAP(L6, O(L)),
	GPIO_CONFIG_MAP(L7, O(L)),
	GPIO_CONFIG_MAP(M0, O(L)),
	GPIO_CONFIG_MAP(M1, O(L)),
	GPIO_CONFIG_MAP(M2, O(L)),
	GPIO_CONFIG_MAP(M3, O(L)),
	GPIO_CONFIG_MAP(M4, O(L)),
	GPIO_CONFIG_MAP(M5, O(L)),
	GPIO_CONFIG_MAP(M6, O(L)),
	GPIO_CONFIG_MAP(M7, O(L)),
	GPIO_CONFIG_MAP(N0, O(L)),
	GPIO_CONFIG_MAP(N1, O(L)),
	GPIO_CONFIG_MAP(N2, O(L)),
	GPIO_CONFIG_MAP(N3, O(H)),
	GPIO_CONFIG_MAP(N4, O(L)),
	GPIO_CONFIG_MAP(N5, O(L)),
	GPIO_CONFIG_MAP(N6, I(PD)),
	GPIO_CONFIG_MAP(N7, I(PD)),
	GPIO_CONFIG_MAP(O0, O(H)),
	GPIO_CONFIG_MAP(O1, A),
	GPIO_CONFIG_MAP(O2, A),
	GPIO_CONFIG_MAP(O3, O(L)),
	GPIO_CONFIG_MAP(O4, I(PU)),
	GPIO_CONFIG_MAP(O5, O(L)),
	GPIO_CONFIG_MAP(O6, O(L)),
	GPIO_CONFIG_MAP(O7, I(NP)),
	GPIO_CONFIG_MAP(P0, O(H)),
	GPIO_CONFIG_MAP(P1, O(L)),
	GPIO_CONFIG_MAP(P2, I(NP)),
	GPIO_CONFIG_MAP(P3, O(L)),
	GPIO_CONFIG_MAP(P4, O(L)),
	GPIO_CONFIG_MAP(P5, I(NP)),
	GPIO_CONFIG_MAP(P6, O(L)),
	GPIO_CONFIG_MAP(P7, O(L)),
	GPIO_CONFIG_MAP(Q0, O(H)),
	GPIO_CONFIG_MAP(Q1, I(PD)),
	GPIO_CONFIG_MAP(Q2, O(L)),
	GPIO_CONFIG_MAP(Q3, SKIP),
	GPIO_CONFIG_MAP(Q4, I(PD)),
	GPIO_CONFIG_MAP(Q5, O(L)),
	GPIO_CONFIG_MAP(Q6, O(L)),
	GPIO_CONFIG_MAP(Q7, O(L)),
	GPIO_CONFIG_MAP(R0, I(PU)),
	GPIO_CONFIG_MAP(R1, O(L)),
	GPIO_CONFIG_MAP(R2, O(H)),
	GPIO_CONFIG_MAP(R3, O(L)),
	GPIO_CONFIG_MAP(R4, O(H)),
	GPIO_CONFIG_MAP(R5, I(PD)),
	GPIO_CONFIG_MAP(R6, O(L)),
	GPIO_CONFIG_MAP(R7, O(L)),
	GPIO_CONFIG_MAP(S0, I(PU)),
	GPIO_CONFIG_MAP(S1, O(H)),
	GPIO_CONFIG_MAP(S2, I(PD)),
	GPIO_CONFIG_MAP(S3, O(L)),
	GPIO_CONFIG_MAP(S4, O(L)),
	GPIO_CONFIG_MAP(S5, O(L)),
	GPIO_CONFIG_MAP(S6, O(L)),
	GPIO_CONFIG_MAP(S7, O(L)),
	GPIO_CONFIG_MAP(T0, O(L)),
	GPIO_CONFIG_MAP(T1, O(L)),
	GPIO_CONFIG_MAP(T2, O(L)),
	GPIO_CONFIG_MAP(T3, O(L)),
	GPIO_CONFIG_MAP(T4, O(L)),
	GPIO_CONFIG_MAP(T5, O(L)),
	GPIO_CONFIG_MAP(T6, O(L)),
	GPIO_CONFIG_MAP(T7, A),
	GPIO_CONFIG_MAP(U0, O(L)),
	GPIO_CONFIG_MAP(U1, O(H)),
	GPIO_CONFIG_MAP(U2, O(L)),
	GPIO_CONFIG_MAP(U3, O(L)),
	GPIO_CONFIG_MAP(U4, O(L)),
	GPIO_CONFIG_MAP(U5, I(PU)),
	GPIO_CONFIG_MAP(U6, I(NP)),
	GPIO_CONFIG_MAP(U7, O(L)),
	GPIO_CONFIG_MAP(V0, I(PU)),
	GPIO_CONFIG_MAP(V1, O(L)),
	GPIO_CONFIG_MAP(V2, O(L)),
	GPIO_CONFIG_MAP(V3, O(L)),
	GPIO_CONFIG_MAP(V4, A),
	GPIO_CONFIG_MAP(V5, A),
	GPIO_CONFIG_MAP(V6, SKIP),
	GPIO_CONFIG_MAP(V7, I(PD)),
	GPIO_CONFIG_MAP(W0, O(L)),
	GPIO_CONFIG_MAP(W1, I(PD)),
	GPIO_CONFIG_MAP(W2, I(PU)),
	GPIO_CONFIG_MAP(W3, I(PU)),
	GPIO_CONFIG_MAP(W4, O(L)),
	GPIO_CONFIG_MAP(W5, O(L)),
	GPIO_CONFIG_MAP(W6, O(L)),
	GPIO_CONFIG_MAP(W7, I(PD)),
	GPIO_CONFIG_MAP(X0, O(L)),
	GPIO_CONFIG_MAP(X1, I(NP)),
	GPIO_CONFIG_MAP(X2, O(L)),
	GPIO_CONFIG_MAP(X3, O(L)),
	GPIO_CONFIG_MAP(X4, SKIP),
	GPIO_CONFIG_MAP(X5, SKIP),
	GPIO_CONFIG_MAP(X6, SKIP),
	GPIO_CONFIG_MAP(X7, SKIP),
	GPIO_CONFIG_MAP(Y0, O(L)),
	GPIO_CONFIG_MAP(Y1, O(L)),
	GPIO_CONFIG_MAP(Y2, O(L)),
	GPIO_CONFIG_MAP(Y3, O(L)),
	GPIO_CONFIG_MAP(Y4, O(L)),
	GPIO_CONFIG_MAP(Y5, O(L)),
	GPIO_CONFIG_MAP(Y6, O(L)),
	GPIO_CONFIG_MAP(Y7, O(L)),
	GPIO_CONFIG_MAP(Z0, O(L)),
	GPIO_CONFIG_MAP(Z1, O(L)),
	GPIO_CONFIG_MAP(Z2, O(L)),
	GPIO_CONFIG_MAP(Z3, O(L)),
	GPIO_CONFIG_MAP(Z4, O(L)),
	GPIO_CONFIG_MAP(Z5, O(L)),
	GPIO_CONFIG_MAP(Z6, A),
	GPIO_CONFIG_MAP(Z7, A),
	GPIO_CONFIG_MAP(AA0, A),
	GPIO_CONFIG_MAP(AA1, A),
	GPIO_CONFIG_MAP(AA2, A),
	GPIO_CONFIG_MAP(AA3, A),
	GPIO_CONFIG_MAP(AA4, A),
	GPIO_CONFIG_MAP(AA5, A),
	GPIO_CONFIG_MAP(AA6, A),
	GPIO_CONFIG_MAP(AA7, A),
	GPIO_CONFIG_MAP(BB0, O(L)),
	GPIO_CONFIG_MAP(BB1, O(L)),
	GPIO_CONFIG_MAP(BB2, O(L)),
	GPIO_CONFIG_MAP(BB3, O(L)),
	GPIO_CONFIG_MAP(BB4, O(L)),
	GPIO_CONFIG_MAP(BB5, O(L)),
	GPIO_CONFIG_MAP(BB6, O(L)),
	GPIO_CONFIG_MAP(BB7, O(L)),
	GPIO_CONFIG_MAP(CC0, O(L)),
	GPIO_CONFIG_MAP(CC1, O(L)),
	GPIO_CONFIG_MAP(CC2, I(PU)),
	GPIO_CONFIG_MAP(CC3, O(H)),
	GPIO_CONFIG_MAP(CC4, A),
	GPIO_CONFIG_MAP(CC5, O(L)),
	GPIO_CONFIG_MAP(CC6, O(L)),
	GPIO_CONFIG_MAP(CC7, O(L)),
	GPIO_CONFIG_MAP(DD0, O(L)),
	GPIO_CONFIG_MAP(DD1, O(L)),
	GPIO_CONFIG_MAP(DD2, O(L)),
	GPIO_CONFIG_MAP(DD3, O(L)),
	GPIO_CONFIG_MAP(DD4, O(L)),
	GPIO_CONFIG_MAP(DD5, O(L)),
	GPIO_CONFIG_MAP(DD6, O(L)),
	GPIO_CONFIG_MAP(DD7, O(L)),
	GPIO_CONFIG_MAP(EE0, O(L)),
	GPIO_CONFIG_MAP(EE1, O(L)),
	GPIO_CONFIG_MAP(EE2, O(L)),
	GPIO_CONFIG_MAP(EE3, O(L)),
};

const char* quo_suspend_gpio_config_xc[TEGRA_NR_GPIOS]= {
	GPIO_CONFIG_MAP(A0, SKIP),  //*
	GPIO_CONFIG_MAP(A1, I(PU)),
	GPIO_CONFIG_MAP(A2, A),
	GPIO_CONFIG_MAP(A3, A),
	GPIO_CONFIG_MAP(A4, A),
	GPIO_CONFIG_MAP(A5, A),
	GPIO_CONFIG_MAP(A6, O(L)),		//*
	GPIO_CONFIG_MAP(A7, O(L)),		//*
	GPIO_CONFIG_MAP(B0, SKIP),		//*
	GPIO_CONFIG_MAP(B1, SKIP),		//*
	GPIO_CONFIG_MAP(B2, O(L)),
	GPIO_CONFIG_MAP(B3, O(L)),
	GPIO_CONFIG_MAP(B4, O(L)),
	GPIO_CONFIG_MAP(B5, O(L)),
	GPIO_CONFIG_MAP(B6, O(L)),
	GPIO_CONFIG_MAP(B7, O(L)),
	GPIO_CONFIG_MAP(C0, O(H)),
	GPIO_CONFIG_MAP(C1, O(L)),
	GPIO_CONFIG_MAP(C2, O(L)),
	GPIO_CONFIG_MAP(C3, I(PD)),
	GPIO_CONFIG_MAP(C4, A),
	GPIO_CONFIG_MAP(C5, A),
	GPIO_CONFIG_MAP(C6, O(L)),
	GPIO_CONFIG_MAP(C7, I(NP)),
	GPIO_CONFIG_MAP(D0, I(NP)),
	GPIO_CONFIG_MAP(D1, O(L)),
	GPIO_CONFIG_MAP(D2, O(L)),
	GPIO_CONFIG_MAP(D3, I(PU)),
	GPIO_CONFIG_MAP(D4, O(L)),
	GPIO_CONFIG_MAP(D5, A),
	GPIO_CONFIG_MAP(D6, A),
	GPIO_CONFIG_MAP(D7, A),
	GPIO_CONFIG_MAP(E0, O(L)),
	GPIO_CONFIG_MAP(E1, O(L)),
	GPIO_CONFIG_MAP(E2, O(L)),
	GPIO_CONFIG_MAP(E3, O(L)),
	GPIO_CONFIG_MAP(E4, O(L)),
	GPIO_CONFIG_MAP(E5, O(L)),
	GPIO_CONFIG_MAP(E6, O(L)),
	GPIO_CONFIG_MAP(E7, O(L)),
	GPIO_CONFIG_MAP(F0, O(L)),
	GPIO_CONFIG_MAP(F1, O(L)),
	GPIO_CONFIG_MAP(F2, O(L)),
	GPIO_CONFIG_MAP(F3, O(L)),
	GPIO_CONFIG_MAP(F4, O(L)),
	GPIO_CONFIG_MAP(F5, O(L)),
	GPIO_CONFIG_MAP(F6, O(L)),
	GPIO_CONFIG_MAP(F7, O(L)),
	GPIO_CONFIG_MAP(G0, I(NP)),
	GPIO_CONFIG_MAP(G1, I(NP)),
	GPIO_CONFIG_MAP(G2, I(NP)),
	GPIO_CONFIG_MAP(G3, I(NP)),
	GPIO_CONFIG_MAP(G4, I(NP)),
	GPIO_CONFIG_MAP(G5, I(NP)),
	GPIO_CONFIG_MAP(G6, I(NP)),
	GPIO_CONFIG_MAP(G7, I(NP)),
	GPIO_CONFIG_MAP(H0, O(L)),
	GPIO_CONFIG_MAP(H1, O(L)),
	GPIO_CONFIG_MAP(H2, O(L)),
	GPIO_CONFIG_MAP(H3, I(NP)),
	GPIO_CONFIG_MAP(H4, O(L)),
	GPIO_CONFIG_MAP(H5, I(NP)),		//*
	GPIO_CONFIG_MAP(H6, I(PU)),
	GPIO_CONFIG_MAP(H7, O(H)),
	GPIO_CONFIG_MAP(I0, I(NP)),
	GPIO_CONFIG_MAP(I1, I(NP)),
	GPIO_CONFIG_MAP(I2, O(L)),
	GPIO_CONFIG_MAP(I3, I(PU)),
	GPIO_CONFIG_MAP(I4, O(L)),
	GPIO_CONFIG_MAP(I5, I(PU)),
	GPIO_CONFIG_MAP(I6, I(PD)),
	GPIO_CONFIG_MAP(I7, O(H)),
	GPIO_CONFIG_MAP(J0, I(NP)),
	GPIO_CONFIG_MAP(J1, O(L)),
	GPIO_CONFIG_MAP(J2, I(PD)),
	GPIO_CONFIG_MAP(J3, O(L)),
	GPIO_CONFIG_MAP(J4, O(L)),
	GPIO_CONFIG_MAP(J5, I(PD)),
	GPIO_CONFIG_MAP(J6, O(L)),
	GPIO_CONFIG_MAP(J7, SKIP),
	GPIO_CONFIG_MAP(K0, I(NP)),
	GPIO_CONFIG_MAP(K1, I(NP)),
	GPIO_CONFIG_MAP(K2, I(NP)),
	GPIO_CONFIG_MAP(K3, O(L)),
	GPIO_CONFIG_MAP(K4, O(L)),
	GPIO_CONFIG_MAP(K5, SKIP),		//*
	GPIO_CONFIG_MAP(K6, O(L)),
	GPIO_CONFIG_MAP(K7, O(L)),
	GPIO_CONFIG_MAP(L0, A),
	GPIO_CONFIG_MAP(L1, A),
	GPIO_CONFIG_MAP(L2, A),
	GPIO_CONFIG_MAP(L3, A),
	GPIO_CONFIG_MAP(L4, A),
	GPIO_CONFIG_MAP(L5, A),
	GPIO_CONFIG_MAP(L6, A),
	GPIO_CONFIG_MAP(L7, A),
	GPIO_CONFIG_MAP(M0, O(L)),
	GPIO_CONFIG_MAP(M1, O(L)),
	GPIO_CONFIG_MAP(M2, O(L)),
	GPIO_CONFIG_MAP(M3, O(L)),
	GPIO_CONFIG_MAP(M4, O(L)),
	GPIO_CONFIG_MAP(M5, O(L)),
	GPIO_CONFIG_MAP(M6, O(L)),
	GPIO_CONFIG_MAP(M7, O(L)),
	GPIO_CONFIG_MAP(N0, O(L)),
	GPIO_CONFIG_MAP(N1, O(L)),
	GPIO_CONFIG_MAP(N2, O(L)),
	GPIO_CONFIG_MAP(N3, O(H)),
	GPIO_CONFIG_MAP(N4, O(L)),
	GPIO_CONFIG_MAP(N5, O(L)),
	GPIO_CONFIG_MAP(N6, I(PD)),
	GPIO_CONFIG_MAP(N7, I(PD)),
	GPIO_CONFIG_MAP(O0, O(H)),
	GPIO_CONFIG_MAP(O1, A),
	GPIO_CONFIG_MAP(O2, A),
	GPIO_CONFIG_MAP(O3, O(L)),
	GPIO_CONFIG_MAP(O4, I(PU)),
	GPIO_CONFIG_MAP(O5, O(L)),
	GPIO_CONFIG_MAP(O6, O(L)),
	GPIO_CONFIG_MAP(O7, O(L)),
	GPIO_CONFIG_MAP(P0, O(H)),
	GPIO_CONFIG_MAP(P1, O(L)),
	GPIO_CONFIG_MAP(P2, I(NP)),
	GPIO_CONFIG_MAP(P3, O(L)),
	GPIO_CONFIG_MAP(P4, O(L)),
	GPIO_CONFIG_MAP(P5, I(NP)),
	GPIO_CONFIG_MAP(P6, O(L)),
	GPIO_CONFIG_MAP(P7, O(L)),
	GPIO_CONFIG_MAP(Q0, O(H)),
	GPIO_CONFIG_MAP(Q1, I(PD)),
	GPIO_CONFIG_MAP(Q2, O(L)),
	GPIO_CONFIG_MAP(Q3, SKIP),
	GPIO_CONFIG_MAP(Q4, I(PD)),
	GPIO_CONFIG_MAP(Q5, I(PD)),
	GPIO_CONFIG_MAP(Q6, O(L)),
	GPIO_CONFIG_MAP(Q7, O(L)),
	GPIO_CONFIG_MAP(R0, I(PU)),
	GPIO_CONFIG_MAP(R1, O(L)),
	GPIO_CONFIG_MAP(R2, O(H)),
	GPIO_CONFIG_MAP(R3, O(L)),
	GPIO_CONFIG_MAP(R4, O(H)),
	GPIO_CONFIG_MAP(R5, I(PD)),
	GPIO_CONFIG_MAP(R6, O(L)),
	GPIO_CONFIG_MAP(R7, O(L)),
	GPIO_CONFIG_MAP(S0, I(PU)),
	GPIO_CONFIG_MAP(S1, O(H)),
	GPIO_CONFIG_MAP(S2, I(PD)),
	GPIO_CONFIG_MAP(S3, O(L)),
	GPIO_CONFIG_MAP(S4, O(L)),
	GPIO_CONFIG_MAP(S5, O(L)),
	GPIO_CONFIG_MAP(S6, O(L)),
	GPIO_CONFIG_MAP(S7, O(L)),
	GPIO_CONFIG_MAP(T0, A),
	GPIO_CONFIG_MAP(T1, A),
	GPIO_CONFIG_MAP(T2, A),
	GPIO_CONFIG_MAP(T3, A),
	GPIO_CONFIG_MAP(T4, A),
	GPIO_CONFIG_MAP(T5, O(L)),
	GPIO_CONFIG_MAP(T6, O(L)),
	GPIO_CONFIG_MAP(T7, A),
	GPIO_CONFIG_MAP(U0, O(L)),
	GPIO_CONFIG_MAP(U1, O(H)),
	GPIO_CONFIG_MAP(U2, O(L)),
	GPIO_CONFIG_MAP(U3, O(L)),
	GPIO_CONFIG_MAP(U4, O(L)),
	GPIO_CONFIG_MAP(U5, I(PU)),
	GPIO_CONFIG_MAP(U6, I(NP)),
	GPIO_CONFIG_MAP(U7, A),
	GPIO_CONFIG_MAP(V0, I(PU)),
	GPIO_CONFIG_MAP(V1, O(L)),
	GPIO_CONFIG_MAP(V2, I(PD)),
	GPIO_CONFIG_MAP(V3, I(PU)),
	GPIO_CONFIG_MAP(V4, A),
	GPIO_CONFIG_MAP(V5, A),
	GPIO_CONFIG_MAP(V6, SKIP),
	GPIO_CONFIG_MAP(V7, I(PD)),
	GPIO_CONFIG_MAP(W0, O(L)),
	GPIO_CONFIG_MAP(W1, O(L)),
	GPIO_CONFIG_MAP(W2, I(PU)),
	GPIO_CONFIG_MAP(W3, I(PU)),
	GPIO_CONFIG_MAP(W4, O(L)),
	GPIO_CONFIG_MAP(W5, O(L)),
	GPIO_CONFIG_MAP(W6, O(L)),
	GPIO_CONFIG_MAP(W7, I(PD)),
	GPIO_CONFIG_MAP(X0, O(L)),
	GPIO_CONFIG_MAP(X1, I(NP)),
	GPIO_CONFIG_MAP(X2, O(L)),
	GPIO_CONFIG_MAP(X3, O(L)),
	GPIO_CONFIG_MAP(X4, SKIP),
	GPIO_CONFIG_MAP(X5, SKIP),
	GPIO_CONFIG_MAP(X6, SKIP),
	GPIO_CONFIG_MAP(X7, SKIP),
	GPIO_CONFIG_MAP(Y0, O(L)),
	GPIO_CONFIG_MAP(Y1, I(PD)),
	GPIO_CONFIG_MAP(Y2, O(L)),
	GPIO_CONFIG_MAP(Y3, O(L)),
	GPIO_CONFIG_MAP(Y4, O(L)),
	GPIO_CONFIG_MAP(Y5, O(L)),
	GPIO_CONFIG_MAP(Y6, O(L)),
	GPIO_CONFIG_MAP(Y7, O(L)),
	GPIO_CONFIG_MAP(Z0, O(L)),
	GPIO_CONFIG_MAP(Z1, O(L)),
	GPIO_CONFIG_MAP(Z2, O(L)),
	GPIO_CONFIG_MAP(Z3, O(L)),
	GPIO_CONFIG_MAP(Z4, SKIP),
	GPIO_CONFIG_MAP(Z5, O(L)),
	GPIO_CONFIG_MAP(Z6, A),
	GPIO_CONFIG_MAP(Z7, A),
	GPIO_CONFIG_MAP(AA0, A),
	GPIO_CONFIG_MAP(AA1, A),
	GPIO_CONFIG_MAP(AA2, A),
	GPIO_CONFIG_MAP(AA3, A),
	GPIO_CONFIG_MAP(AA4, A),
	GPIO_CONFIG_MAP(AA5, A),
	GPIO_CONFIG_MAP(AA6, A),
	GPIO_CONFIG_MAP(AA7, A),
	GPIO_CONFIG_MAP(BB0, I(PD)),
	GPIO_CONFIG_MAP(BB1, O(L)),
	GPIO_CONFIG_MAP(BB2, O(L)),
	GPIO_CONFIG_MAP(BB3, O(L)),
	GPIO_CONFIG_MAP(BB4, O(L)),
	GPIO_CONFIG_MAP(BB5, O(L)),
	GPIO_CONFIG_MAP(BB6, O(L)),
	GPIO_CONFIG_MAP(BB7, O(L)),
	GPIO_CONFIG_MAP(CC0, O(L)),
	GPIO_CONFIG_MAP(CC1, O(L)),
	GPIO_CONFIG_MAP(CC2, I(PU)),
	GPIO_CONFIG_MAP(CC3, O(H)),
	GPIO_CONFIG_MAP(CC4, A),
	GPIO_CONFIG_MAP(CC5, O(L)),
	GPIO_CONFIG_MAP(CC6, O(L)),
	GPIO_CONFIG_MAP(CC7, O(L)),
	GPIO_CONFIG_MAP(DD0, A),
	GPIO_CONFIG_MAP(DD1, A),
	GPIO_CONFIG_MAP(DD2, A),
	GPIO_CONFIG_MAP(DD3, O(L)),
	GPIO_CONFIG_MAP(DD4, A),
	GPIO_CONFIG_MAP(DD5, A),
	GPIO_CONFIG_MAP(DD6, A),
	GPIO_CONFIG_MAP(DD7, O(L)),
	GPIO_CONFIG_MAP(EE0, O(L)),
	GPIO_CONFIG_MAP(EE1, O(L)),
	GPIO_CONFIG_MAP(EE2, A),
	GPIO_CONFIG_MAP(EE3, O(L)),
};

const char* quo_suspend_gpio_config_xd[TEGRA_NR_GPIOS]= {
	GPIO_CONFIG_MAP(A0, SKIP),  //*
	GPIO_CONFIG_MAP(A1, I(PU)),
	GPIO_CONFIG_MAP(A2, A),
	GPIO_CONFIG_MAP(A3, A),
	GPIO_CONFIG_MAP(A4, A),
	GPIO_CONFIG_MAP(A5, A),
	GPIO_CONFIG_MAP(A6, O(L)),		//*
	GPIO_CONFIG_MAP(A7, O(L)),		//*
	GPIO_CONFIG_MAP(B0, SKIP),		//*
	GPIO_CONFIG_MAP(B1, SKIP),		//*
	GPIO_CONFIG_MAP(B2, O(L)),
	GPIO_CONFIG_MAP(B3, O(L)),
	GPIO_CONFIG_MAP(B4, O(L)),
	GPIO_CONFIG_MAP(B5, O(L)),
	GPIO_CONFIG_MAP(B6, O(L)),
	GPIO_CONFIG_MAP(B7, O(L)),
	GPIO_CONFIG_MAP(C0, O(H)),
	GPIO_CONFIG_MAP(C1, O(L)),
	GPIO_CONFIG_MAP(C2, O(L)),
	GPIO_CONFIG_MAP(C3, I(PD)),
	GPIO_CONFIG_MAP(C4, A),
	GPIO_CONFIG_MAP(C5, A),
	GPIO_CONFIG_MAP(C6, O(L)),
	GPIO_CONFIG_MAP(C7, I(NP)),
	GPIO_CONFIG_MAP(D0, I(NP)),
	GPIO_CONFIG_MAP(D1, O(L)),
	GPIO_CONFIG_MAP(D2, O(L)),
	GPIO_CONFIG_MAP(D3, I(PU)),
	GPIO_CONFIG_MAP(D4, O(L)),
	GPIO_CONFIG_MAP(D5, O(L)),
	GPIO_CONFIG_MAP(D6, O(L)),
	GPIO_CONFIG_MAP(D7, O(L)),
	GPIO_CONFIG_MAP(E0, O(L)),
	GPIO_CONFIG_MAP(E1, O(L)),
	GPIO_CONFIG_MAP(E2, O(L)),
	GPIO_CONFIG_MAP(E3, O(L)),
	GPIO_CONFIG_MAP(E4, O(L)),
	GPIO_CONFIG_MAP(E5, O(L)),
	GPIO_CONFIG_MAP(E6, O(L)),
	GPIO_CONFIG_MAP(E7, O(L)),
	GPIO_CONFIG_MAP(F0, O(L)),
	GPIO_CONFIG_MAP(F1, O(L)),
	GPIO_CONFIG_MAP(F2, O(L)),
	GPIO_CONFIG_MAP(F3, O(L)),
	GPIO_CONFIG_MAP(F4, O(L)),
	GPIO_CONFIG_MAP(F5, O(L)),
	GPIO_CONFIG_MAP(F6, O(L)),
	GPIO_CONFIG_MAP(F7, O(L)),
	GPIO_CONFIG_MAP(G0, I(NP)),
	GPIO_CONFIG_MAP(G1, I(NP)),
	GPIO_CONFIG_MAP(G2, I(NP)),
	GPIO_CONFIG_MAP(G3, I(NP)),
	GPIO_CONFIG_MAP(G4, I(NP)),
	GPIO_CONFIG_MAP(G5, I(NP)),
	GPIO_CONFIG_MAP(G6, I(NP)),
	GPIO_CONFIG_MAP(G7, I(NP)),
	GPIO_CONFIG_MAP(H0, O(L)),
	GPIO_CONFIG_MAP(H1, O(L)),
	GPIO_CONFIG_MAP(H2, O(L)),
	GPIO_CONFIG_MAP(H3, I(NP)),
	GPIO_CONFIG_MAP(H4, O(L)),
	GPIO_CONFIG_MAP(H5, I(NP)),		//*
	GPIO_CONFIG_MAP(H6, I(PU)),
	GPIO_CONFIG_MAP(H7, O(L)),
	GPIO_CONFIG_MAP(I0, I(NP)),
	GPIO_CONFIG_MAP(I1, I(NP)),
	GPIO_CONFIG_MAP(I2, O(L)),
	GPIO_CONFIG_MAP(I3, I(PU)),
	GPIO_CONFIG_MAP(I4, O(L)),
	GPIO_CONFIG_MAP(I5, I(PU)),
	GPIO_CONFIG_MAP(I6, I(PD)),
	GPIO_CONFIG_MAP(I7, O(H)),
	GPIO_CONFIG_MAP(J0, I(NP)),
	GPIO_CONFIG_MAP(J1, O(L)),
	GPIO_CONFIG_MAP(J2, I(PD)),
	GPIO_CONFIG_MAP(J3, O(L)),
	GPIO_CONFIG_MAP(J4, O(L)),
	GPIO_CONFIG_MAP(J5, I(PD)),
	GPIO_CONFIG_MAP(J6, O(L)),
	GPIO_CONFIG_MAP(J7, SKIP),
	GPIO_CONFIG_MAP(K0, I(NP)),
	GPIO_CONFIG_MAP(K1, I(NP)),
	GPIO_CONFIG_MAP(K2, I(NP)),
	GPIO_CONFIG_MAP(K3, O(L)),
	GPIO_CONFIG_MAP(K4, O(L)),
	GPIO_CONFIG_MAP(K5, SKIP),		//*
	GPIO_CONFIG_MAP(K6, O(L)),
	GPIO_CONFIG_MAP(K7, O(L)),
	GPIO_CONFIG_MAP(L0, O(L)),
	GPIO_CONFIG_MAP(L1, O(L)),
	GPIO_CONFIG_MAP(L2, O(L)),
	GPIO_CONFIG_MAP(L3, O(L)),
	GPIO_CONFIG_MAP(L4, O(L)),
	GPIO_CONFIG_MAP(L5, O(L)),
	GPIO_CONFIG_MAP(L6, O(L)),
	GPIO_CONFIG_MAP(L7, O(L)),
	GPIO_CONFIG_MAP(M0, O(L)),
	GPIO_CONFIG_MAP(M1, O(L)),
	GPIO_CONFIG_MAP(M2, O(L)),
	GPIO_CONFIG_MAP(M3, O(L)),
	GPIO_CONFIG_MAP(M4, O(L)),
	GPIO_CONFIG_MAP(M5, O(L)),
	GPIO_CONFIG_MAP(M6, O(L)),
	GPIO_CONFIG_MAP(M7, O(L)),
	GPIO_CONFIG_MAP(N0, O(L)),
	GPIO_CONFIG_MAP(N1, O(L)),
	GPIO_CONFIG_MAP(N2, O(L)),
	GPIO_CONFIG_MAP(N3, O(H)),
	GPIO_CONFIG_MAP(N4, O(L)),
	GPIO_CONFIG_MAP(N5, O(L)),
	GPIO_CONFIG_MAP(N6, I(PD)),
	GPIO_CONFIG_MAP(N7, I(PD)),
	GPIO_CONFIG_MAP(O0, O(H)),
	GPIO_CONFIG_MAP(O1, A),
	GPIO_CONFIG_MAP(O2, A),
	GPIO_CONFIG_MAP(O3, O(L)),
	GPIO_CONFIG_MAP(O4, O(L)),
	GPIO_CONFIG_MAP(O5, O(L)),
	GPIO_CONFIG_MAP(O6, O(L)),
	GPIO_CONFIG_MAP(O7, O(H)),
	GPIO_CONFIG_MAP(P0, O(H)),
	GPIO_CONFIG_MAP(P1, O(L)),
	GPIO_CONFIG_MAP(P2, I(NP)),
	GPIO_CONFIG_MAP(P3, O(L)),
	GPIO_CONFIG_MAP(P4, O(L)),
	GPIO_CONFIG_MAP(P5, I(NP)),
	GPIO_CONFIG_MAP(P6, O(L)),
	GPIO_CONFIG_MAP(P7, O(L)),
	GPIO_CONFIG_MAP(Q0, O(H)),
	GPIO_CONFIG_MAP(Q1, I(PD)),
	GPIO_CONFIG_MAP(Q2, O(L)),
	GPIO_CONFIG_MAP(Q3, SKIP),
	GPIO_CONFIG_MAP(Q4, I(PD)),
	GPIO_CONFIG_MAP(Q5, I(PD)),
	GPIO_CONFIG_MAP(Q6, O(L)),
	GPIO_CONFIG_MAP(Q7, O(L)),
	GPIO_CONFIG_MAP(R0, I(PU)),
	GPIO_CONFIG_MAP(R1, O(L)),
	GPIO_CONFIG_MAP(R2, O(H)),
	GPIO_CONFIG_MAP(R3, O(L)),
	GPIO_CONFIG_MAP(R4, O(H)),
	GPIO_CONFIG_MAP(R5, I(PD)),
	GPIO_CONFIG_MAP(R6, O(L)),
	GPIO_CONFIG_MAP(R7, O(L)),
	GPIO_CONFIG_MAP(S0, I(PU)),
	GPIO_CONFIG_MAP(S1, O(L)),
	GPIO_CONFIG_MAP(S2, I(PU)),
	GPIO_CONFIG_MAP(S3, O(L)),
	GPIO_CONFIG_MAP(S4, O(L)),
	GPIO_CONFIG_MAP(S5, O(L)),
	GPIO_CONFIG_MAP(S6, O(L)),
	GPIO_CONFIG_MAP(S7, O(L)),
	GPIO_CONFIG_MAP(T0, O(L)),
	GPIO_CONFIG_MAP(T1, O(L)),
	GPIO_CONFIG_MAP(T2, O(L)),
	GPIO_CONFIG_MAP(T3, O(L)),
	GPIO_CONFIG_MAP(T4, O(L)),
	GPIO_CONFIG_MAP(T5, O(L)),
	GPIO_CONFIG_MAP(T6, O(L)),
	GPIO_CONFIG_MAP(T7, A),
	GPIO_CONFIG_MAP(U0, O(L)),
	GPIO_CONFIG_MAP(U1, O(L)),
	GPIO_CONFIG_MAP(U2, O(L)),
	GPIO_CONFIG_MAP(U3, O(L)),
	GPIO_CONFIG_MAP(U4, O(L)),
	GPIO_CONFIG_MAP(U5, I(PU)),
	GPIO_CONFIG_MAP(U6, I(NP)),
	GPIO_CONFIG_MAP(U7, O(L)),
	GPIO_CONFIG_MAP(V0, I(PU)),
	GPIO_CONFIG_MAP(V1, O(L)),
	GPIO_CONFIG_MAP(V2, I(PD)),
	GPIO_CONFIG_MAP(V3, I(PU)),
	GPIO_CONFIG_MAP(V4, A),
	GPIO_CONFIG_MAP(V5, A),
	GPIO_CONFIG_MAP(V6, SKIP),
	GPIO_CONFIG_MAP(V7, I(PD)),
	GPIO_CONFIG_MAP(W0, O(L)),
	GPIO_CONFIG_MAP(W1, O(L)),
	GPIO_CONFIG_MAP(W2, I(PU)),
	GPIO_CONFIG_MAP(W3, I(PU)),
	GPIO_CONFIG_MAP(W4, O(L)),
	GPIO_CONFIG_MAP(W5, O(L)),
	GPIO_CONFIG_MAP(W6, O(L)),
	GPIO_CONFIG_MAP(W7, I(PD)),
	GPIO_CONFIG_MAP(X0, O(L)),
	GPIO_CONFIG_MAP(X1, I(NP)),
	GPIO_CONFIG_MAP(X2, O(L)),
	GPIO_CONFIG_MAP(X3, O(L)),
	GPIO_CONFIG_MAP(X4, SKIP),
	GPIO_CONFIG_MAP(X5, SKIP),
	GPIO_CONFIG_MAP(X6, SKIP),
	GPIO_CONFIG_MAP(X7, SKIP),
	GPIO_CONFIG_MAP(Y0, O(L)),
	GPIO_CONFIG_MAP(Y1, I(PD)),
	GPIO_CONFIG_MAP(Y2, O(L)),
	GPIO_CONFIG_MAP(Y3, O(L)),
	GPIO_CONFIG_MAP(Y4, O(L)),
	GPIO_CONFIG_MAP(Y5, O(L)),
	GPIO_CONFIG_MAP(Y6, O(L)),
	GPIO_CONFIG_MAP(Y7, O(L)),
	GPIO_CONFIG_MAP(Z0, O(L)),
	GPIO_CONFIG_MAP(Z1, O(L)),
	GPIO_CONFIG_MAP(Z2, O(L)),
	GPIO_CONFIG_MAP(Z3, O(L)),
	GPIO_CONFIG_MAP(Z4, SKIP),
	GPIO_CONFIG_MAP(Z5, O(H)),
	GPIO_CONFIG_MAP(Z6, A),
	GPIO_CONFIG_MAP(Z7, A),
	GPIO_CONFIG_MAP(AA0, A),
	GPIO_CONFIG_MAP(AA1, A),
	GPIO_CONFIG_MAP(AA2, A),
	GPIO_CONFIG_MAP(AA3, A),
	GPIO_CONFIG_MAP(AA4, A),
	GPIO_CONFIG_MAP(AA5, A),
	GPIO_CONFIG_MAP(AA6, A),
	GPIO_CONFIG_MAP(AA7, A),
	GPIO_CONFIG_MAP(BB0, I(PD)),
	GPIO_CONFIG_MAP(BB1, O(L)),
	GPIO_CONFIG_MAP(BB2, O(L)),
	GPIO_CONFIG_MAP(BB3, O(L)),
	GPIO_CONFIG_MAP(BB4, O(L)),
	GPIO_CONFIG_MAP(BB5, O(L)),
	GPIO_CONFIG_MAP(BB6, O(L)),
	GPIO_CONFIG_MAP(BB7, O(L)),
	GPIO_CONFIG_MAP(CC0, O(L)),
	GPIO_CONFIG_MAP(CC1, O(L)),
	GPIO_CONFIG_MAP(CC2, I(PU)),
	GPIO_CONFIG_MAP(CC3, O(H)),
	GPIO_CONFIG_MAP(CC4, A),
	GPIO_CONFIG_MAP(CC5, O(L)),
	GPIO_CONFIG_MAP(CC6, O(L)),
	GPIO_CONFIG_MAP(CC7, O(L)),
	GPIO_CONFIG_MAP(DD0, O(L)),
	GPIO_CONFIG_MAP(DD1, O(L)),
	GPIO_CONFIG_MAP(DD2, O(L)),
	GPIO_CONFIG_MAP(DD3, O(L)),
	GPIO_CONFIG_MAP(DD4, O(L)),
	GPIO_CONFIG_MAP(DD5, O(L)),
	GPIO_CONFIG_MAP(DD6, O(L)),
	GPIO_CONFIG_MAP(DD7, O(L)),
	GPIO_CONFIG_MAP(EE0, O(L)),
	GPIO_CONFIG_MAP(EE1, O(L)),
	GPIO_CONFIG_MAP(EE2, O(L)),
	GPIO_CONFIG_MAP(EE3, O(L)),
};

static int __gpio_setup(int gpio, int state)
{
	static bool has_auto_requested[TEGRA_NR_GPIOS] = {false}; // init false

	enum tegra_pingroup   ball;
	enum tegra_pullupdown pupd;
	int ret;
	const char *name;

	if (gpio == TEGRA_GPIO_PEE3 || gpio == TEGRA_GPIO_PU7)
	{
		ball = INVALID_BALL;
		name = "<auto>";
	} else
	{
		ball = gpio_to_pingroup[gpio];
		name = tegra_soc_pingroups[ball].name;
	}

	if (! has_auto_requested[gpio])
	{
		ret = gpio_request(gpio, name);
		if (ret < 0)
		{
			if (ret == -EBUSY)
			{
				pr_warn("[GPIO_SETUP] force to obtain requested gpio: %d (%s)\n",
						gpio, name);
			} else {
				pr_err("[GPIO_SETUP] gpio_request fail on %d (%s), "
						"error code: %d\n",
						gpio, name, ret);
				gpio_free(gpio);
				return ret;
			}
		}
		else
			has_auto_requested[gpio] = true;
	}

	/* gpio_export(gpio, false); */
	if (state & GPIO_SETUP_OUTPUT) {
		gpio_direction_output(gpio,
				state == GPIO_SETUP_OUTPUT_HIGH ? 1 : 0);
		tegra_pinmux_set_tristate(ball, TEGRA_TRI_NORMAL);
		tegra_pinmux_set_pullupdown(ball, TEGRA_PUPD_NORMAL);
		tegra_pinmux_set_io(ball, TEGRA_PIN_OUTPUT);
	} else { /* INPUT */
		gpio_direction_input(gpio);
		switch (state)
		{
			case GPIO_SETUP_INPUT_PULL_UP:
				pupd = TEGRA_PUPD_PULL_UP;
			break;
			case GPIO_SETUP_INPUT_PULL_DOWN:
				pupd = TEGRA_PUPD_PULL_DOWN;
			break;
			case GPIO_SETUP_INPUT_NO_PULL:
			default:
				pupd = TEGRA_PUPD_NORMAL;
			break;
		}
		tegra_pinmux_set_tristate(ball, TEGRA_TRI_TRISTATE);
		tegra_pinmux_set_pullupdown(ball, pupd);
		tegra_pinmux_set_io(ball, TEGRA_PIN_INPUT);
	}
	tegra_gpio_enable(gpio);

	return 0;
}

void local_gpio_config_test(char** gpioTable){
	int i;
	for (i = 0; i < TEGRA_GPIO_INVALID; ++i){
		if (strcmp(gpioTable[i], "O(H)") == 0){
			__gpio_setup(i, GPIO_SETUP_OUTPUT_HIGH);
		} else if (strcmp(gpioTable[i], "O(L)") == 0) {
			__gpio_setup(i,  GPIO_SETUP_OUTPUT_LOW);
		} else if (strcmp(gpioTable[i], "I(PU)") == 0) {
			__gpio_setup(i,  GPIO_SETUP_INPUT_PULL_UP);
		} else if (strcmp(gpioTable[i], "I(PD)") == 0) {
			__gpio_setup(i,  GPIO_SETUP_INPUT_PULL_DOWN);
		} else if (strcmp(gpioTable[i], "I(NP)") == 0) {
			__gpio_setup(i,  GPIO_SETUP_INPUT_NO_PULL);
		} else if (strcmp(gpioTable[i], "A") == 0) {
			tegra_gpio_disable(i);
		} else if (strcmp(gpioTable[i], "A(PU)") == 0){
			__gpio_setup(i,  GPIO_SETUP_INPUT_PULL_UP);
			tegra_gpio_disable(i);
		}
	}
}

#define GPIO_CONFIG_MAP(gpio, value) \
    [TEGRA_GPIO_P ## gpio] = # value


const char* enr_xc_suspend_gpio_config[TEGRA_NR_GPIOS]= {
	GPIO_CONFIG_MAP(A0, O(L)),
	GPIO_CONFIG_MAP(A1, A),
	GPIO_CONFIG_MAP(A2, O(L)),
	GPIO_CONFIG_MAP(A3, O(L)),
	GPIO_CONFIG_MAP(A4, O(L)),
	GPIO_CONFIG_MAP(A5, O(L)),
	GPIO_CONFIG_MAP(A6, O(L)),
	GPIO_CONFIG_MAP(A7, A(PU)),
	GPIO_CONFIG_MAP(B0, O(L)),
	GPIO_CONFIG_MAP(B1, O(L)),
	GPIO_CONFIG_MAP(B2, O(H)),
	GPIO_CONFIG_MAP(B3, O(L)),
	GPIO_CONFIG_MAP(B4, A(PU)),
	GPIO_CONFIG_MAP(B5, A(PU)),
	GPIO_CONFIG_MAP(B6, A(PU)),
	GPIO_CONFIG_MAP(B7, A(PU)),
	GPIO_CONFIG_MAP(C0, O(H)),
	GPIO_CONFIG_MAP(C1, O(L)),
	GPIO_CONFIG_MAP(C2, O(L)),
	GPIO_CONFIG_MAP(C3, O(L)),
	GPIO_CONFIG_MAP(C4, A),
	GPIO_CONFIG_MAP(C5, A),
	GPIO_CONFIG_MAP(C6, O(L)),
	GPIO_CONFIG_MAP(C7, I(PU)),
	GPIO_CONFIG_MAP(D0, O(L)),
	GPIO_CONFIG_MAP(D1, O(L)),
	GPIO_CONFIG_MAP(D2, O(L)),
	GPIO_CONFIG_MAP(D3, O(L)),
	GPIO_CONFIG_MAP(D4, O(L)),
	GPIO_CONFIG_MAP(D5, O(L)),
	GPIO_CONFIG_MAP(D6, O(L)),
	GPIO_CONFIG_MAP(D7, O(L)),
	GPIO_CONFIG_MAP(E0, O(L)),
	GPIO_CONFIG_MAP(E1, O(L)),
	GPIO_CONFIG_MAP(E2, O(L)),
	GPIO_CONFIG_MAP(E3, O(L)),
	GPIO_CONFIG_MAP(E4, O(L)),
	GPIO_CONFIG_MAP(E5, O(L)),
	GPIO_CONFIG_MAP(E6, O(H)),
	GPIO_CONFIG_MAP(E7, O(L)),
	GPIO_CONFIG_MAP(F0, O(L)),
	GPIO_CONFIG_MAP(F1, O(L)),
	GPIO_CONFIG_MAP(F2, O(L)),
	GPIO_CONFIG_MAP(F3, O(H)),
	GPIO_CONFIG_MAP(F4, O(L)),
	GPIO_CONFIG_MAP(F5, O(L)),
	GPIO_CONFIG_MAP(F6, O(L)),
	GPIO_CONFIG_MAP(F7, O(L)),
	GPIO_CONFIG_MAP(G0, I(NP)),
	GPIO_CONFIG_MAP(G1, I(NP)),
	GPIO_CONFIG_MAP(G2, I(NP)),
	GPIO_CONFIG_MAP(G3, I(NP)),
	GPIO_CONFIG_MAP(G4, I(NP)),
	GPIO_CONFIG_MAP(G5, I(NP)),
	GPIO_CONFIG_MAP(G6, I(NP)),
	GPIO_CONFIG_MAP(G7, I(NP)),
	GPIO_CONFIG_MAP(H0, O(L)),
	GPIO_CONFIG_MAP(H1, O(L)),
	GPIO_CONFIG_MAP(H2, O(L)),
	GPIO_CONFIG_MAP(H3, I(NP)),
	GPIO_CONFIG_MAP(H4, O(L)),
	GPIO_CONFIG_MAP(H5, O(L)),
	GPIO_CONFIG_MAP(H6, O(L)),
	GPIO_CONFIG_MAP(H7, O(L)),
	GPIO_CONFIG_MAP(I0, I(NP)),
	GPIO_CONFIG_MAP(I1, I(NP)),
	GPIO_CONFIG_MAP(I2, O(L)),
	GPIO_CONFIG_MAP(I3, O(L)),
	GPIO_CONFIG_MAP(I4, O(L)),
	GPIO_CONFIG_MAP(I5, I(NP)),
	GPIO_CONFIG_MAP(I6, I(NP)),
	GPIO_CONFIG_MAP(I7, O(L)),
	GPIO_CONFIG_MAP(J0, O(L)),
	GPIO_CONFIG_MAP(J1, I(NP)),
	GPIO_CONFIG_MAP(J2, I(NP)),
	GPIO_CONFIG_MAP(J3, O(L)),
	GPIO_CONFIG_MAP(J4, O(L)),
	GPIO_CONFIG_MAP(J5, O(L)),
	GPIO_CONFIG_MAP(J6, O(L)),
	GPIO_CONFIG_MAP(J7, O(L)),
	GPIO_CONFIG_MAP(K0, I(NP)),
	GPIO_CONFIG_MAP(K1, I(NP)),
	GPIO_CONFIG_MAP(K2, I(PU)),
	GPIO_CONFIG_MAP(K3, O(L)),
	GPIO_CONFIG_MAP(K4, O(L)),
	GPIO_CONFIG_MAP(K5, O(L)),
	GPIO_CONFIG_MAP(K6, O(L)),
	GPIO_CONFIG_MAP(K7, O(L)),
	GPIO_CONFIG_MAP(L0, O(L)),
	GPIO_CONFIG_MAP(L1, O(L)),
	GPIO_CONFIG_MAP(L2, O(L)),
	GPIO_CONFIG_MAP(L3, O(L)),
	GPIO_CONFIG_MAP(L4, O(L)),
	GPIO_CONFIG_MAP(L5, O(L)),
	GPIO_CONFIG_MAP(L6, O(L)),
	GPIO_CONFIG_MAP(L7, O(L)),
	GPIO_CONFIG_MAP(M0, I(NP)),
	GPIO_CONFIG_MAP(M1, I(NP)),
	GPIO_CONFIG_MAP(M2, O(L)),
	GPIO_CONFIG_MAP(M3, O(L)),
	GPIO_CONFIG_MAP(M4, O(L)),
	GPIO_CONFIG_MAP(M5, O(H)),
	GPIO_CONFIG_MAP(M6, O(L)),
	GPIO_CONFIG_MAP(M7, O(L)),
	GPIO_CONFIG_MAP(N0, O(L)),
	GPIO_CONFIG_MAP(N1, O(L)),
	GPIO_CONFIG_MAP(N2, I(NP)),
	GPIO_CONFIG_MAP(N3, O(L)),
	GPIO_CONFIG_MAP(N4, O(L)),
	GPIO_CONFIG_MAP(N5, O(L)),
	GPIO_CONFIG_MAP(N6, O(L)),
	GPIO_CONFIG_MAP(N7, I(NP)),
	GPIO_CONFIG_MAP(O0, O(L)),
	GPIO_CONFIG_MAP(O1, A),
	GPIO_CONFIG_MAP(O2, A),
	GPIO_CONFIG_MAP(O3, O(L)),
	GPIO_CONFIG_MAP(O4, I(NP)),
	GPIO_CONFIG_MAP(O5, I(PU)),
	GPIO_CONFIG_MAP(O6, O(L)),
	GPIO_CONFIG_MAP(O7, O(L)),
	GPIO_CONFIG_MAP(P0, O(L)),
	GPIO_CONFIG_MAP(P1, O(L)),
	GPIO_CONFIG_MAP(P2, O(L)),
	GPIO_CONFIG_MAP(P3, O(L)),
	GPIO_CONFIG_MAP(P4, O(L)),
	GPIO_CONFIG_MAP(P5, O(L)),
	GPIO_CONFIG_MAP(P6, O(L)),
	GPIO_CONFIG_MAP(P7, O(L)),
	GPIO_CONFIG_MAP(Q0, O(L)),
	GPIO_CONFIG_MAP(Q1, O(L)),
	GPIO_CONFIG_MAP(Q2, O(L)),
	GPIO_CONFIG_MAP(Q3, O(L)),
	GPIO_CONFIG_MAP(Q4, O(L)),
	GPIO_CONFIG_MAP(Q5, O(L)),
	GPIO_CONFIG_MAP(Q6, O(L)),
	GPIO_CONFIG_MAP(Q7, O(L)),
	GPIO_CONFIG_MAP(R0, I(NP)),
	GPIO_CONFIG_MAP(R1, O(L)),
	GPIO_CONFIG_MAP(R2, O(H)),
	GPIO_CONFIG_MAP(R3, O(L)),
	GPIO_CONFIG_MAP(R4, O(L)),
	GPIO_CONFIG_MAP(R5, O(L)),
	GPIO_CONFIG_MAP(R6, I(NP)), //
	GPIO_CONFIG_MAP(R7, I(NP)), //
	GPIO_CONFIG_MAP(S0, I(PU)),
	GPIO_CONFIG_MAP(S1, O(L)),
	GPIO_CONFIG_MAP(S2, I(NP)),
	GPIO_CONFIG_MAP(S3, O(L)),
	GPIO_CONFIG_MAP(S4, O(L)),
	GPIO_CONFIG_MAP(S5, O(L)),
	GPIO_CONFIG_MAP(S6, O(L)),
	GPIO_CONFIG_MAP(S7, O(L)),
	GPIO_CONFIG_MAP(T0, O(L)),
	GPIO_CONFIG_MAP(T1, O(L)),
	GPIO_CONFIG_MAP(T2, O(L)),
	GPIO_CONFIG_MAP(T3, O(L)),
	GPIO_CONFIG_MAP(T4, O(L)),
	GPIO_CONFIG_MAP(T5, A),
	GPIO_CONFIG_MAP(T6, A),
	GPIO_CONFIG_MAP(T7, A(PU)),
	GPIO_CONFIG_MAP(U0, O(L)),
	GPIO_CONFIG_MAP(U1, O(L)),
	GPIO_CONFIG_MAP(U2, O(L)),
	GPIO_CONFIG_MAP(U3, O(H)),
	GPIO_CONFIG_MAP(U4, I(NP)),
	GPIO_CONFIG_MAP(U5, O(L)),
	GPIO_CONFIG_MAP(U6, I(PU)),
	GPIO_CONFIG_MAP(U7, O(L)),
	GPIO_CONFIG_MAP(V0, I(NP)),
	GPIO_CONFIG_MAP(V1, I(NP)),
	GPIO_CONFIG_MAP(V2, O(L)),
	GPIO_CONFIG_MAP(V3, O(L)),
	GPIO_CONFIG_MAP(V4, A),
	GPIO_CONFIG_MAP(V5, A),
	GPIO_CONFIG_MAP(V6, I(PU)),
	GPIO_CONFIG_MAP(V7, O(L)),
	GPIO_CONFIG_MAP(W0, I(PU)),
	GPIO_CONFIG_MAP(W1, O(L)),
	GPIO_CONFIG_MAP(W2, I(PU)),
	GPIO_CONFIG_MAP(W3, I(PU)),
	GPIO_CONFIG_MAP(W4, O(L)),
	GPIO_CONFIG_MAP(W5, O(L)),
	GPIO_CONFIG_MAP(W6, A),
	GPIO_CONFIG_MAP(W7, A),
	GPIO_CONFIG_MAP(X0, A),
	GPIO_CONFIG_MAP(X1, A),
	GPIO_CONFIG_MAP(X2, A),
	GPIO_CONFIG_MAP(X3, A),
	GPIO_CONFIG_MAP(X4, O(L)),
	GPIO_CONFIG_MAP(X5, I(PU)),
	GPIO_CONFIG_MAP(X6, O(L)),
	GPIO_CONFIG_MAP(X7, O(L)),
	GPIO_CONFIG_MAP(Y0, O(L)),
	GPIO_CONFIG_MAP(Y1, O(L)),
	GPIO_CONFIG_MAP(Y2, O(L)),
	GPIO_CONFIG_MAP(Y3, O(H)),
	GPIO_CONFIG_MAP(Y4, O(L)),
	GPIO_CONFIG_MAP(Y5, O(H)), //I(H)
	GPIO_CONFIG_MAP(Y6, I(NP)),
	GPIO_CONFIG_MAP(Y7, O(L)),
	GPIO_CONFIG_MAP(Z0, O(H)),
	GPIO_CONFIG_MAP(Z1, O(L)),
	GPIO_CONFIG_MAP(Z2, O(H)),
	GPIO_CONFIG_MAP(Z3, O(L)),
	GPIO_CONFIG_MAP(Z4, O(L)),
	GPIO_CONFIG_MAP(Z5, O(L)),
	GPIO_CONFIG_MAP(Z6, A),
	GPIO_CONFIG_MAP(Z7, A),
	GPIO_CONFIG_MAP(AA0, A(PU)),
	GPIO_CONFIG_MAP(AA1, A(PU)),
	GPIO_CONFIG_MAP(AA2, A(PU)),
	GPIO_CONFIG_MAP(AA3, A(PU)),
	GPIO_CONFIG_MAP(AA4, A(PU)),
	GPIO_CONFIG_MAP(AA5, A(PU)),
	GPIO_CONFIG_MAP(AA6, A(PU)),
	GPIO_CONFIG_MAP(AA7, A(PU)),
	GPIO_CONFIG_MAP(BB0, O(L)),
	GPIO_CONFIG_MAP(BB1, O(L)),
	GPIO_CONFIG_MAP(BB2, O(L)),
	GPIO_CONFIG_MAP(BB3, O(L)),
	GPIO_CONFIG_MAP(BB4, O(L)),
	GPIO_CONFIG_MAP(BB5, O(L)),
	GPIO_CONFIG_MAP(BB6, I(NP)),
	GPIO_CONFIG_MAP(BB7, O(L)),
	GPIO_CONFIG_MAP(CC0, O(L)),
	GPIO_CONFIG_MAP(CC1, O(L)),
	GPIO_CONFIG_MAP(CC2, I(PU)),
	GPIO_CONFIG_MAP(CC3, A),
	GPIO_CONFIG_MAP(CC4, O(L)),
	GPIO_CONFIG_MAP(CC5, O(L)),
	GPIO_CONFIG_MAP(CC6, O(L)),
	GPIO_CONFIG_MAP(CC7, O(L)),
	GPIO_CONFIG_MAP(DD0, O(L)),
	GPIO_CONFIG_MAP(DD1, O(L)),
	GPIO_CONFIG_MAP(DD2, O(L)),
	GPIO_CONFIG_MAP(DD3, O(L)),
	GPIO_CONFIG_MAP(DD4, O(L)),
	GPIO_CONFIG_MAP(DD5, O(L)),
	GPIO_CONFIG_MAP(DD6, O(L)),
	GPIO_CONFIG_MAP(DD7, O(L)),
	GPIO_CONFIG_MAP(EE0, O(L)),
	GPIO_CONFIG_MAP(EE1, I(NP)),
	GPIO_CONFIG_MAP(EE2, O(L)),
	GPIO_CONFIG_MAP(EE3, O(L)),
};

void quo_xa_unused_gpio_init(void)
{
	DEBUG_ENTRY();
	GPIO_SETUP(K3,  INPUT_PULL_UP);
	GPIO_SETUP(K4,  INPUT_PULL_UP);
	GPIO_SETUP(Z4,  INPUT_PULL_UP);
	GPIO_SETUP(D2,  INPUT_PULL_DOWN);
	GPIO_SETUP(I3,  INPUT_PULL_UP);
	GPIO_SETUP(Q6,  INPUT_PULL_DOWN);
	GPIO_SETUP(Q7,  INPUT_PULL_DOWN);
	GPIO_SETUP(S3,  INPUT_PULL_DOWN);
	GPIO_SETUP(S4,  INPUT_PULL_DOWN);
	GPIO_SETUP(S5,  INPUT_PULL_DOWN);
	GPIO_SETUP(S6,  INPUT_PULL_DOWN);
	GPIO_SETUP(S7,  INPUT_PULL_DOWN);
	GPIO_SETUP(CC5, INPUT_PULL_UP);
	GPIO_SETUP(CC6, INPUT_PULL_DOWN);
	GPIO_SETUP(CC7, INPUT_PULL_DOWN);
	GPIO_SETUP(DD3, INPUT_PULL_DOWN);
	GPIO_SETUP(DD7, INPUT_PULL_DOWN);
	GPIO_SETUP(W5,  OUTPUT_HIGH);

	GPIO_SETUP(G0,  INPUT_NO_PULL);
	GPIO_SETUP(G1,  INPUT_NO_PULL);
	GPIO_SETUP(G2,  INPUT_NO_PULL);
	GPIO_SETUP(G3,  INPUT_NO_PULL);
	GPIO_SETUP(G4,  INPUT_NO_PULL);
	GPIO_SETUP(G5,  INPUT_NO_PULL);
	GPIO_SETUP(I0,  INPUT_NO_PULL);

	GPIO_SETUP(EE0, OUTPUT_LOW);
	GPIO_SETUP(C7,	INPUT_PULL_UP); //1-WIRE_INT
	GPIO_SETUP(I1,	INPUT_NO_PULL);	//USB_RECOVERY
	GPIO_SETUP(K0,	INPUT_NO_PULL); //ARM_JTAG0
	GPIO_SETUP(K1,	INPUT_NO_PULL);	//ARM_JTAG1
	GPIO_SETUP(N1,	INPUT_NO_PULL);	//BB_KEY2
	GPIO_SETUP(Q0,	INPUT_NO_PULL);	//RF_BD_ID1
	GPIO_SETUP(Q5,	INPUT_PULL_UP);	//BB_KEY1
}
void quo_xb_no_owner_gpio_init(void)
{
	DEBUG_ENTRY();
	GPIO_SETUP(C6,  OUTPUT_LOW);		  /*AP2BB_SLAVE_WAKEUP*/
	GPIO_SETUP(C7,  INPUT_NO_PULL);		  /*AP2BB_SLAVE_WAKEUP*/

	GPIO_SETUP(D2,  OUTPUT_LOW);		  /*reserved*/
	GPIO_SETUP(D5,  OUTPUT_LOW);		  /*reserved*/
	GPIO_SETUP(D7,  OUTPUT_LOW);		  /*reserved*/

	GPIO_SETUP(G0,  INPUT_NO_PULL);	      /*BOOT_SEL_0*/
	GPIO_SETUP(G1,  INPUT_NO_PULL);       /*BOOT_SEL_1*/
	GPIO_SETUP(G2,  INPUT_NO_PULL);       /*BOOT_SEL_2*/
	GPIO_SETUP(G3,  INPUT_NO_PULL);       /*BOOT_SEL_3*/
	GPIO_SETUP(G4,  INPUT_NO_PULL);       /*RAM_CODE_0*/
	GPIO_SETUP(G5,  INPUT_NO_PULL);       /*RAM_CODE_1*/

	GPIO_SETUP(I0,  INPUT_NO_PULL);       /*NOR_BOOT#*/
	GPIO_SETUP(I1,	INPUT_NO_PULL);	      /*FORCE_RECOVER_R#_1*/
	GPIO_SETUP(I2,  OUTPUT_LOW);          /*FUSE_3V3_EN*/
	//GPIO_SETUP(I3,  INPUT_PULL_UP);       /*HDMI_5V_OCP#*/
	GPIO_SETUP(I7,  OUTPUT_HIGH);         /*RF_BD_ID2*/

	GPIO_SETUP(K0,  INPUT_NO_PULL);       /*ARM_JTAG0*/
	GPIO_SETUP(K1,  INPUT_NO_PULL);       /*ARM_JTAG1*/
	GPIO_SETUP(K2,  OUTPUT_LOW);          /*AP2BB_RST_PWRDWN#*/
	GPIO_SETUP(K3,  OUTPUT_LOW);          /*reserved*/
	GPIO_SETUP(K4,  OUTPUT_LOW);          /*reserved*/
	GPIO_SETUP(K6,  OUTPUT_LOW);          /*AP2BB_HOST_ACTIVE*/
	GPIO_SETUP(K7,  OUTPUT_LOW);          /*BB_VDD_EN*/

	GPIO_SETUP(N1,  OUTPUT_LOW);          /*BB_KEY2*/
	GPIO_SETUP(N2,  OUTPUT_LOW);          /*BB2AP_ACK*/
	GPIO_SETUP(N4,  OUTPUT_LOW);          /*reserved*/

	GPIO_SETUP(O5,  OUTPUT_LOW);          /*BB2AP_FATAL_INT*/

	GPIO_SETUP(Q0,	OUTPUT_HIGH);	      /*RF_BD_ID1*/
	GPIO_SETUP(Q2,	OUTPUT_LOW);	      /*reserved*/
	GPIO_SETUP(Q5,	OUTPUT_LOW);	      /*BB_KEY1*/
	GPIO_SETUP(Q6,	OUTPUT_LOW);	      /*reserved*/
	GPIO_SETUP(Q7,	OUTPUT_LOW);	      /*reserved*/

	GPIO_SETUP(S3,  OUTPUT_LOW);		  /*reserved*/
	GPIO_SETUP(S4,  OUTPUT_LOW);	      /*reserved*/
	GPIO_SETUP(S5,  OUTPUT_LOW);		  /*reserved*/
	GPIO_SETUP(S6,  OUTPUT_LOW);		  /*reserved*/
	GPIO_SETUP(S7,  OUTPUT_LOW);		  /*reserved*/

	GPIO_SETUP(T0,  OUTPUT_LOW);		  /*reserved*/
	GPIO_SETUP(T1,  OUTPUT_LOW);		  /*reserved*/
	GPIO_SETUP(T2,  OUTPUT_LOW);		  /*reserved*/
	GPIO_SETUP(T3,  OUTPUT_LOW);		  /*reserved*/
	GPIO_SETUP(T4,  OUTPUT_LOW);		  /*reserved*/

	GPIO_SETUP(U2,  OUTPUT_LOW);		  /*BB_SPI_FLASH_SEL#*/
	GPIO_SETUP(U7,  OUTPUT_LOW);		  /*reserved*/

	GPIO_SETUP(V1,  OUTPUT_LOW);		  /*BB2AP_HOST_WAKEUP*/
	GPIO_SETUP(V2,  OUTPUT_LOW);		  /*reserved*/
	GPIO_SETUP(V3,  OUTPUT_LOW);		  /*reserved*/

	GPIO_SETUP(W0,  OUTPUT_LOW);		  /*AP2BB_PWRON#*/
	GPIO_SETUP(W5,  OUTPUT_LOW);          /*reserved*/

	GPIO_SETUP(Y0,  OUTPUT_LOW);          /*UART_AT_TX*/
	GPIO_SETUP(Y1,  OUTPUT_LOW);          /*UART_AT_RX*/
	GPIO_SETUP(Y2,  OUTPUT_LOW);          /*UART_AT_CTS_N#*/
	GPIO_SETUP(Y3,  OUTPUT_LOW);          /*UART_AT_RTS_N#*/

	GPIO_SETUP(Z2,  OUTPUT_LOW);          /*AP2BB_RST#*/
	GPIO_SETUP(Z4,  OUTPUT_LOW);          /*reserved#*/

	GPIO_SETUP(BB6,  OUTPUT_LOW);         /*BB_RESET_STATUS*/

	GPIO_SETUP(CC5, OUTPUT_LOW);          /*reserved*/
	GPIO_SETUP(CC6, OUTPUT_LOW);		  /*reserved*/
	GPIO_SETUP(CC7, OUTPUT_LOW);          /*reserved*/

	GPIO_SETUP(DD0, OUTPUT_LOW);          /*reserved*/
	GPIO_SETUP(DD1, OUTPUT_LOW);          /*reserved*/
	GPIO_SETUP(DD2, OUTPUT_LOW);          /*reserved*/
	GPIO_SETUP(DD3, OUTPUT_LOW);          /*reserved*/
	GPIO_SETUP(DD4, OUTPUT_LOW);          /*reserved*/
	GPIO_SETUP(DD5, OUTPUT_LOW);          /*reserved*/
	GPIO_SETUP(DD6, OUTPUT_LOW);          /*reserved*/
	GPIO_SETUP(DD7, OUTPUT_LOW);	      /*reserved*/

}

void quo_xc_no_owner_gpio_init(void)
{
	DEBUG_ENTRY();
	GPIO_SETUP(C1,  OUTPUT_LOW);		  /*USB_BB_EN*/
	GPIO_SETUP(C2,  OUTPUT_LOW);		  /*GPS_UART_TXD*/
	GPIO_SETUP(C3,  OUTPUT_LOW);		  /*GPS_UART_RXD*/
	GPIO_SETUP(C6,  OUTPUT_LOW);		  /*AP2BB_SLAVE_WAKEUP*/
	GPIO_SETUP(C7,  INPUT_NO_PULL);		  /*AP2BB_SLAVE_WAKEUP*/

	GPIO_SETUP(G0,  INPUT_NO_PULL);	      /*BOOT_SEL_0*/
	GPIO_SETUP(G1,  INPUT_NO_PULL);       /*BOOT_SEL_1*/
	GPIO_SETUP(G2,  INPUT_NO_PULL);       /*BOOT_SEL_2*/
	GPIO_SETUP(G3,  INPUT_NO_PULL);       /*BOOT_SEL_3*/
	GPIO_SETUP(G4,  INPUT_NO_PULL);       /*RAM_CODE_0*/
	GPIO_SETUP(G5,  INPUT_NO_PULL);       /*RAM_CODE_1*/
	GPIO_SETUP(G6,  INPUT_NO_PULL);       /*RAM_CODE_2*/
	GPIO_SETUP(G7,  INPUT_NO_PULL);       /*RAM_CODE_3*/

	GPIO_SETUP(I0,  INPUT_NO_PULL);       /*NOR_BOOT#*/
	GPIO_SETUP(I1,	INPUT_NO_PULL);	      /*FORCE_RECOVER_R#_1*/
	GPIO_SETUP(I2,  OUTPUT_LOW);          /*FUSE_3V3_EN*/
	//GPIO_SETUP(I3,  INPUT_PULL_UP);       /*HDMI_5V_OCP#*/
	GPIO_SETUP(I7,  OUTPUT_HIGH);         /*RF_BD_ID2*/

	GPIO_SETUP(J5,  INPUT_PULL_DOWN);          /*GPS_UART_CTS*/
	GPIO_SETUP(J6,  OUTPUT_LOW);          /*GPS_UART_RTS*/

	GPIO_SETUP(K0,  INPUT_NO_PULL);       /*ARM_JTAG0*/
	GPIO_SETUP(K1,  INPUT_NO_PULL);       /*ARM_JTAG1*/
//	GPIO_SETUP(K2,  OUTPUT_LOW);          /*AP2BB_RST_PWRDWN#*/
	GPIO_SETUP(K3,  OUTPUT_LOW);          /*reserved*/
	GPIO_SETUP(K4,  OUTPUT_LOW);          /*reserved*/
	GPIO_SETUP(K6,  OUTPUT_LOW);          /*AP2BB_HOST_ACTIVE*/
	GPIO_SETUP(K7,  OUTPUT_LOW);          /*BB_VDD_EN*/

//	GPIO_SETUP(N1,  OUTPUT_LOW);          /*BB_KEY2*/
	GPIO_SETUP(N2,  OUTPUT_LOW);          /*BB2AP_ACK*/
//	GPIO_SETUP(N4,  OUTPUT_LOW);          /*reserved*/

	GPIO_SETUP(O5,  OUTPUT_LOW);          /*BB2AP_FATAL_INT*/
	GPIO_SETUP(O7,  OUTPUT_LOW);    	  /*reserved*/

	GPIO_SETUP(P4,  OUTPUT_LOW);    	  /*AUD_BTPCM_SYNC_1*/
	GPIO_SETUP(P5,  INPUT_NO_PULL);    	  /*AUD_BTPCM_DOUT_1*/
	GPIO_SETUP(P6,  OUTPUT_LOW);    	  /*AUD_BTPCM_DIN_1*/
	GPIO_SETUP(P7,  OUTPUT_LOW);    	  /*AUD_BTPCM_CLK_1*/

	GPIO_SETUP(Q0,	OUTPUT_HIGH);	      /*RF_BD_ID1*/
	GPIO_SETUP(Q1,	INPUT_PULL_DOWN);	      /*MB_ID0*/
	GPIO_SETUP(Q2,	OUTPUT_LOW);	      /*reserved*/
	GPIO_SETUP(Q5,	INPUT_PULL_DOWN);	      /*REGION_ID*/
	GPIO_SETUP(Q6,	OUTPUT_LOW);	      /*reserved*/
	GPIO_SETUP(Q7,	OUTPUT_LOW);	      /*reserved*/

	GPIO_SETUP(R0,	INPUT_PULL_UP);	      /*GPIO_1V8_1WIRE*/
	GPIO_SETUP(R1,	OUTPUT_LOW);	      /*Reserve*/
	GPIO_SETUP(R5,  INPUT_PULL_DOWN);		  /*MB_ID1*/
	GPIO_SETUP(R6,  OUTPUT_LOW);		  /*reserved*/
	GPIO_SETUP(R7,  OUTPUT_LOW);		  /*GPS_EN*/

	GPIO_SETUP(S3,  OUTPUT_LOW);		  /*reserved*/
	GPIO_SETUP(S4,  OUTPUT_LOW);	      /*reserved*/
	GPIO_SETUP(S5,  OUTPUT_LOW);		  /*reserved*/
	GPIO_SETUP(S6,  OUTPUT_LOW);		  /*reserved*/
	GPIO_SETUP(S7,  OUTPUT_LOW);		  /*reserved*/

	GPIO_SETUP(U2,  OUTPUT_LOW);		  /*BB_SPI_FLASH_SEL#*/
	GPIO_SETUP(U4,  OUTPUT_LOW);		  /*reserved#*/

	GPIO_SETUP(V1,  OUTPUT_LOW);		  /*BB2AP_HOST_WAKEUP*/
	GPIO_SETUP(V2,  INPUT_PULL_DOWN);		  /*TW_ID*/


	GPIO_SETUP(W0,  OUTPUT_LOW);		  /*AP2BB_PWRON#*/
//	GPIO_SETUP(W5,  OUTPUT_LOW);          /*reserved*/

//	GPIO_SETUP(Y0,  OUTPUT_LOW);          /*UART_AT_TX*/
//	GPIO_SETUP(Y1,  OUTPUT_LOW);          /*UART_AT_RX*/
	GPIO_SETUP(Y2,  OUTPUT_LOW);          /*reserved*/
	GPIO_SETUP(Y3,  OUTPUT_LOW);          /*reserved*/

	GPIO_SETUP(Z2,  OUTPUT_LOW);          /*AP2BB_RST#*/
//	GPIO_SETUP(Z4,  OUTPUT_LOW);          /*reserved#*/

	GPIO_SETUP(BB6,  OUTPUT_LOW);         /*BB_RESET_STATUS*/

	GPIO_SETUP(CC5, OUTPUT_LOW);          /*reserved*/
	GPIO_SETUP(CC6, OUTPUT_LOW);		  /*reserved*/
	GPIO_SETUP(CC7, OUTPUT_LOW);          /*reserved*/

	GPIO_SETUP(DD3, OUTPUT_LOW);          /*reserved*/
	GPIO_SETUP(DD7, OUTPUT_LOW);	      /*reserved*/

	GPIO_SETUP(EE0, OUTPUT_LOW);	      /*reserved*/
}

void quo_xd_no_owner_gpio_init(void)
{
	DEBUG_ENTRY();
	GPIO_SETUP(C1,  OUTPUT_LOW);		  /*reserved*/
	GPIO_SETUP(C6,  OUTPUT_LOW);		  /*AP2BB_SLAVE_WAKEUP*/
	GPIO_SETUP(C7,  INPUT_NO_PULL);		  /*AP2BB_SLAVE_WAKEUP*/

	GPIO_SETUP(G0,  INPUT_NO_PULL);	      /*BOOT_SEL_0*/
	GPIO_SETUP(G1,  INPUT_NO_PULL);       /*BOOT_SEL_1*/
	GPIO_SETUP(G2,  INPUT_NO_PULL);       /*BOOT_SEL_2*/
	GPIO_SETUP(G3,  INPUT_NO_PULL);       /*BOOT_SEL_3*/
	GPIO_SETUP(G4,  INPUT_NO_PULL);       /*RAM_CODE_0*/
	GPIO_SETUP(G5,  INPUT_NO_PULL);       /*RAM_CODE_1*/

	GPIO_SETUP(I0,  INPUT_NO_PULL);       /*NOR_BOOT#*/
	GPIO_SETUP(I1,	INPUT_NO_PULL);	      /*FORCE_RECOVER_R#_1*/
	GPIO_SETUP(I2,  OUTPUT_LOW);          /*FUSE_3V3_EN*/
	//GPIO_SETUP(I3,  INPUT_PULL_UP);       /*HDMI_5V_OCP#*/
	GPIO_SETUP(I7,  OUTPUT_HIGH);         /*RF_BD_ID2*/

	GPIO_SETUP(K0,  INPUT_NO_PULL);       /*ARM_JTAG0*/
	GPIO_SETUP(K1,  INPUT_NO_PULL);       /*ARM_JTAG1*/
//	GPIO_SETUP(K2,  OUTPUT_LOW);          /*AP2BB_RST_PWRDWN#*/
	GPIO_SETUP(K3,  OUTPUT_LOW);          /*AP2BB_RST_PWRDWN_N_1*/
	GPIO_SETUP(K4,  OUTPUT_LOW);          /*reserved*/
	GPIO_SETUP(K6,  OUTPUT_LOW);          /*AP2BB_HOST_ACTIVE*/
	GPIO_SETUP(K7,  OUTPUT_LOW);          /*BB_VDD_EN*/

//	GPIO_SETUP(N1,  OUTPUT_LOW);          /*BB_KEY2*/
	GPIO_SETUP(N2,  OUTPUT_LOW);          /*BB2AP_ACK*/
//	GPIO_SETUP(N4,  OUTPUT_LOW);          /*reserved*/

	GPIO_SETUP(O4,  OUTPUT_LOW);          /*WW_IRQ_1*/
	GPIO_SETUP(O5,  OUTPUT_LOW);          /*BB2AP_FATAL_INT*/

	GPIO_SETUP(Q0,	OUTPUT_HIGH);	      /*RF_BD_ID1*/
	GPIO_SETUP(Q2,	OUTPUT_LOW);	      /*reserved*/
	GPIO_SETUP(Q5,	OUTPUT_LOW);	      /*BB_KEY1*/
	GPIO_SETUP(Q6,	OUTPUT_LOW);	      /*reserved*/
	GPIO_SETUP(Q7,	OUTPUT_LOW);	      /*reserved*/

	GPIO_SETUP(R6,  OUTPUT_LOW);		  /*reserved*/
	GPIO_SETUP(R7,  OUTPUT_LOW);		  /*GPS_EN*/

	GPIO_SETUP(S1,  OUTPUT_LOW);		  /*reserved*/
	GPIO_SETUP(S3,  OUTPUT_LOW);		  /*reserved*/
	GPIO_SETUP(S4,  OUTPUT_LOW);	      /*reserved*/
	GPIO_SETUP(S5,  OUTPUT_LOW);		  /*reserved*/
	GPIO_SETUP(S6,  OUTPUT_LOW);		  /*reserved*/
	GPIO_SETUP(S7,  OUTPUT_LOW);		  /*reserved*/

	GPIO_SETUP(U4,  OUTPUT_LOW);		  /*reserved#*/

	GPIO_SETUP(V1,  OUTPUT_LOW);		  /*BB2AP_HOST_WAKEUP*/
//	GPIO_SETUP(V2,  OUTPUT_LOW);		  /*reserved*/
//	GPIO_SETUP(V3,  OUTPUT_LOW);		  /*reserved*/

	GPIO_SETUP(W0,  OUTPUT_LOW);		  /*AP2BB_PWRON#*/
//	GPIO_SETUP(W5,  OUTPUT_LOW);          /*reserved*/

//	GPIO_SETUP(Y0,  OUTPUT_LOW);          /*UART_AT_TX*/
//	GPIO_SETUP(Y1,  OUTPUT_LOW);          /*UART_AT_RX*/
	GPIO_SETUP(Y2,  OUTPUT_LOW);          /*reserved*/
	GPIO_SETUP(Y3,  OUTPUT_LOW);          /*reserved*/

	GPIO_SETUP(Z2,  OUTPUT_LOW);          /*AP2BB_RST#*/
//	GPIO_SETUP(Z4,  OUTPUT_LOW);          /*reserved#*/

	GPIO_SETUP(BB6,  OUTPUT_LOW);         /*BB_RESET_STATUS*/

	GPIO_SETUP(CC5, OUTPUT_LOW);          /*reserved*/
	GPIO_SETUP(CC6, OUTPUT_LOW);		  /*reserved*/
	GPIO_SETUP(CC7, OUTPUT_LOW);          /*reserved*/

	GPIO_SETUP(DD3, OUTPUT_LOW);          /*reserved*/
	GPIO_SETUP(DD7, OUTPUT_LOW);	      /*reserved*/

	GPIO_SETUP(EE0, OUTPUT_LOW);	      /*reserved*/
}

void ble_xa_unused_gpio_init(void)
{
	DEBUG_ENTRY();
	GPIO_SETUP(A0, OUTPUT_LOW);
	GPIO_SETUP(D0, OUTPUT_LOW);
	GPIO_SETUP(D1, OUTPUT_LOW);
	GPIO_SETUP(D2, OUTPUT_LOW);
	GPIO_SETUP(D3, OUTPUT_LOW);
	GPIO_SETUP(D4, OUTPUT_LOW);
	GPIO_SETUP(E3, OUTPUT_LOW);
	GPIO_SETUP(E4, OUTPUT_LOW);
	GPIO_SETUP(F0, OUTPUT_LOW);
	GPIO_SETUP(F2, OUTPUT_LOW);
	GPIO_SETUP(F4, OUTPUT_LOW);
	GPIO_SETUP(F5, OUTPUT_LOW);
	GPIO_SETUP(H0, OUTPUT_LOW);
	GPIO_SETUP(H1, OUTPUT_LOW);
	GPIO_SETUP(H2, OUTPUT_LOW);
	GPIO_SETUP(H3, OUTPUT_LOW);
	GPIO_SETUP(H4, OUTPUT_LOW);
	GPIO_SETUP(H5, OUTPUT_LOW);
	GPIO_SETUP(H6, OUTPUT_LOW);
	GPIO_SETUP(H7, OUTPUT_LOW);
	GPIO_SETUP(I2, OUTPUT_LOW);
	GPIO_SETUP(I3, OUTPUT_LOW);
	GPIO_SETUP(I4, OUTPUT_LOW);
	GPIO_SETUP(I7, OUTPUT_LOW);
	GPIO_SETUP(J3, OUTPUT_LOW);
	GPIO_SETUP(J4, OUTPUT_LOW);
	GPIO_SETUP(J6, OUTPUT_LOW);
	GPIO_SETUP(K0, INPUT_NO_PULL);
	GPIO_SETUP(K1, INPUT_NO_PULL);
	GPIO_SETUP(K3, OUTPUT_LOW);
	GPIO_SETUP(K4, OUTPUT_LOW);
	GPIO_SETUP(K5, OUTPUT_LOW);
	GPIO_SETUP(K6, OUTPUT_LOW);
	GPIO_SETUP(M3, OUTPUT_LOW);
	GPIO_SETUP(M5, OUTPUT_LOW);
	GPIO_SETUP(M6, OUTPUT_LOW);
	GPIO_SETUP(N4, OUTPUT_LOW);
	GPIO_SETUP(N5, OUTPUT_LOW);
	GPIO_SETUP(N7, OUTPUT_LOW);
	GPIO_SETUP(O0, OUTPUT_LOW);
	GPIO_SETUP(O3, OUTPUT_LOW);
	GPIO_SETUP(O6, OUTPUT_LOW);
	GPIO_SETUP(O7, OUTPUT_LOW);
	GPIO_SETUP(Q0, OUTPUT_LOW);
	GPIO_SETUP(Q1, OUTPUT_LOW);
	GPIO_SETUP(Q2, OUTPUT_LOW);
	GPIO_SETUP(Q3, OUTPUT_LOW);
	GPIO_SETUP(Q4, OUTPUT_LOW);
	GPIO_SETUP(Q5, OUTPUT_LOW);
	GPIO_SETUP(Q6, OUTPUT_LOW);
	GPIO_SETUP(Q7, OUTPUT_LOW);
	GPIO_SETUP(R0, OUTPUT_LOW);
	GPIO_SETUP(R2, OUTPUT_LOW);
	GPIO_SETUP(R3, OUTPUT_LOW);
	GPIO_SETUP(R4, OUTPUT_LOW);
	GPIO_SETUP(R5, OUTPUT_LOW);
	GPIO_SETUP(S1, OUTPUT_LOW);
	GPIO_SETUP(U1, OUTPUT_LOW);
	GPIO_SETUP(U2, OUTPUT_LOW);
	GPIO_SETUP(U3, OUTPUT_LOW);
	GPIO_SETUP(V3, OUTPUT_LOW);
	GPIO_SETUP(V4, OUTPUT_LOW);
	GPIO_SETUP(V5, OUTPUT_LOW);
	GPIO_SETUP(V7, OUTPUT_LOW);
	GPIO_SETUP(X4, OUTPUT_LOW);
	GPIO_SETUP(X6, OUTPUT_LOW);
	GPIO_SETUP(Y0, OUTPUT_LOW);
	GPIO_SETUP(Y4, OUTPUT_LOW);
	GPIO_SETUP(Y5, OUTPUT_LOW);
	GPIO_SETUP(Y6, OUTPUT_LOW);
	GPIO_SETUP(Y7, OUTPUT_LOW);
	GPIO_SETUP(Z0, OUTPUT_LOW);
	GPIO_SETUP(Z1, OUTPUT_LOW);
	GPIO_SETUP(Z3, OUTPUT_LOW);
	GPIO_SETUP(Z4, OUTPUT_LOW);
	GPIO_SETUP(Z5, INPUT_NO_PULL);
	GPIO_SETUP(BB6, OUTPUT_LOW);
	GPIO_SETUP(CC5, OUTPUT_LOW);
	GPIO_SETUP(EE0, OUTPUT_LOW);
	GPIO_SETUP(EE1, OUTPUT_LOW);
	GPIO_SETUP(EE3, OUTPUT_LOW);
	GPIO_SETUP(G0, INPUT_NO_PULL);
	GPIO_SETUP(G1, INPUT_NO_PULL);
	GPIO_SETUP(G2, INPUT_NO_PULL);
	GPIO_SETUP(G3, INPUT_NO_PULL);
	GPIO_SETUP(G4, INPUT_NO_PULL);
	GPIO_SETUP(G5, INPUT_NO_PULL);
	GPIO_SETUP(G6, INPUT_NO_PULL);
	GPIO_SETUP(G7, INPUT_NO_PULL);

	//GPIO_SETUP(J1, INPUT_PULL_DOWN);
	GPIO_SETUP(V6, INPUT_PULL_UP);
	GPIO_SETUP(I0, INPUT_NO_PULL);
	GPIO_SETUP(I1, INPUT_NO_PULL);
	GPIO_SETUP(P4, OUTPUT_LOW);	//BT
	GPIO_SETUP(P5, OUTPUT_LOW);	//BT
	GPIO_SETUP(P6, OUTPUT_LOW);	//BT
	GPIO_SETUP(P7, OUTPUT_LOW);	//BT
}

void ble_xb_no_owner_gpio_init(void)
{
	DEBUG_ENTRY();
	GPIO_SETUP(A0, OUTPUT_LOW);
	GPIO_SETUP(I0,  INPUT_NO_PULL); /* GMI_OE#   */
	GPIO_SETUP(I1,  INPUT_NO_PULL); /* GMI_WR#   */
	GPIO_SETUP(V6,  INPUT_PULL_UP); /* REGION_ID */
	GPIO_SETUP(S2, INPUT_PULL_UP); /* USB_ID */
}

void ble_xb_unused_gpio_init(void)
{
	DEBUG_ENTRY();
}

void enr_xc_no_owner_gpio_init(void)
{
	DEBUG_ENTRY();
	GPIO_SETUP(G0, INPUT_NO_PULL); //BOOT_SEL_0
	GPIO_SETUP(G1, INPUT_NO_PULL); //BOOT_SEL_1
	GPIO_SETUP(G2, INPUT_NO_PULL); //BOOT_SEL_2
	GPIO_SETUP(G3, INPUT_NO_PULL); //BOOT_SEL_3
	GPIO_SETUP(G4, INPUT_NO_PULL); //RAM_CODE_0
	GPIO_SETUP(G5, INPUT_NO_PULL); //RAM_CODE_1
	GPIO_SETUP(G6, INPUT_NO_PULL); //RAM_CODE_2
	GPIO_SETUP(G7, INPUT_NO_PULL); //RAM_CODE_3

	//GPIO_SETUP(V6, INPUT_PULL_UP); //REGION_ID
	GPIO_SETUP(I0, INPUT_NO_PULL); //GMI_WR#:FORCER_ECOVERY
	GPIO_SETUP(I1, INPUT_NO_PULL); //GMI_OE#
	GPIO_SETUP(K0, INPUT_NO_PULL); //ARM_JTAG0
	GPIO_SETUP(K1, INPUT_NO_PULL); //ARM_JTAG1
	GPIO_SETUP(Z5, OUTPUT_LOW); //SYS_CLK_REQ
	GPIO_SETUP(U3, OUTPUT_HIGH); //WARM_RESET_0#

}

void enr_xd_no_owner_gpio_init(void)
{
	DEBUG_ENTRY();
	GPIO_SETUP(G0, INPUT_NO_PULL); //BOOT_SEL_0
	GPIO_SETUP(G1, INPUT_NO_PULL); //BOOT_SEL_1
	GPIO_SETUP(G2, INPUT_NO_PULL); //BOOT_SEL_2
	GPIO_SETUP(G3, INPUT_NO_PULL); //BOOT_SEL_3
	GPIO_SETUP(G4, INPUT_NO_PULL); //RAM_CODE_0
	GPIO_SETUP(G5, INPUT_NO_PULL); //RAM_CODE_1
	GPIO_SETUP(G6, INPUT_NO_PULL); //RAM_CODE_2
	GPIO_SETUP(G7, INPUT_NO_PULL); //RAM_CODE_3

	//GPIO_SETUP(V6, INPUT_PULL_UP); //REGION_ID
	GPIO_SETUP(I0, INPUT_NO_PULL); //GMI_WR#:FORCER_ECOVERY
	GPIO_SETUP(I1, INPUT_NO_PULL); //GMI_OE#
	GPIO_SETUP(K0, INPUT_NO_PULL); //ARM_JTAG0
	GPIO_SETUP(K1, INPUT_NO_PULL); //ARM_JTAG1
	GPIO_SETUP(Z5, OUTPUT_LOW); //SYS_CLK_REQ
	GPIO_SETUP(U3, OUTPUT_HIGH); //WARM_RESET_0#

}

void enr_xe_no_owner_gpio_init(void)
{
	DEBUG_ENTRY();
	GPIO_SETUP(G0, INPUT_NO_PULL); //BOOT_SEL_0
	GPIO_SETUP(G1, INPUT_NO_PULL); //BOOT_SEL_1
	GPIO_SETUP(G2, INPUT_NO_PULL); //BOOT_SEL_2
	GPIO_SETUP(G3, INPUT_NO_PULL); //BOOT_SEL_3
	GPIO_SETUP(G4, INPUT_NO_PULL); //RAM_CODE_0
	GPIO_SETUP(G5, INPUT_NO_PULL); //RAM_CODE_1
	GPIO_SETUP(G6, INPUT_NO_PULL); //RAM_CODE_2
	GPIO_SETUP(G7, INPUT_NO_PULL); //RAM_CODE_3

	//GPIO_SETUP(V6, INPUT_PULL_UP); //REGION_ID
	GPIO_SETUP(I0, INPUT_NO_PULL); //GMI_WR#:FORCER_ECOVERY
	GPIO_SETUP(I1, INPUT_NO_PULL); //GMI_OE#
	GPIO_SETUP(K0, INPUT_NO_PULL); //ARM_JTAG0
	GPIO_SETUP(K1, INPUT_NO_PULL); //ARM_JTAG1
	GPIO_SETUP(Z5, OUTPUT_LOW); //SYS_CLK_REQ
	GPIO_SETUP(U3, OUTPUT_HIGH); //WARM_RESET_0#

}

#ifdef CONFIG_PM
void enr_xc_no_owner_gpio_suspend(void)
{
	pr_debug("[htc-gpio] entering edge_evt_no_owner_gpio_suspend\n");
	GPIO_SETUP(F7, OUTPUT_LOW);  //PMU_MSECURE
}

void enr_xc_no_owner_gpio_resume(void)
{
	pr_debug("[htc-gpio] entering edge_evt_no_owner_gpio_resume\n");
	GPIO_SETUP(F7, OUTPUT_HIGH); //PMU_MSECURE
}

void quo_xa_unused_gpio_suspend(void)
{
	DEBUG_ENTRY();
	GPIO_SETUP(K3,  INPUT_PULL_DOWN);
	GPIO_SETUP(K4,  INPUT_PULL_DOWN);
	GPIO_SETUP(Z4,  INPUT_PULL_DOWN);
	GPIO_SETUP(D2,  INPUT_PULL_DOWN);
	GPIO_SETUP(I3,  INPUT_PULL_UP);
	GPIO_SETUP(Q6,  INPUT_PULL_DOWN);
	GPIO_SETUP(Q7,  INPUT_PULL_DOWN);
	GPIO_SETUP(S3,  INPUT_NO_PULL);
	GPIO_SETUP(S4,  INPUT_NO_PULL);
	GPIO_SETUP(S5,  INPUT_NO_PULL);
	GPIO_SETUP(S6,  INPUT_NO_PULL);
	GPIO_SETUP(S7,  INPUT_NO_PULL);
	GPIO_SETUP(W5,  INPUT_PULL_DOWN);
	GPIO_SETUP(CC5, INPUT_PULL_DOWN);
	GPIO_SETUP(CC6, INPUT_PULL_DOWN);
	GPIO_SETUP(CC7, INPUT_PULL_DOWN);
	GPIO_SETUP(DD3, INPUT_PULL_DOWN);
	GPIO_SETUP(DD7, INPUT_PULL_DOWN);

	GPIO_SETUP(EE0, OUTPUT_LOW);
	GPIO_SETUP(C7,	INPUT_PULL_UP); //1-WIRE_INT
	GPIO_SETUP(I1,	INPUT_NO_PULL);	//USB_RECOVERY
	GPIO_SETUP(K0,	INPUT_NO_PULL); //ARM_JTAG0
	GPIO_SETUP(K1,	INPUT_NO_PULL);	//ARM_JTAG1
	GPIO_SETUP(N1,	INPUT_NO_PULL); //BB_KEY2
	GPIO_SETUP(Q0,	INPUT_NO_PULL); //RF_BD_ID1
	GPIO_SETUP(Q5,	INPUT_NO_PULL); //BB_KEY1
}

void quo_xb_no_owner_gpio_suspend(void)
{
	DEBUG_ENTRY();
	GPIO_SETUP(A1,  INPUT_PULL_UP);       /*BT_UART_CTS#*/

	GPIO_SETUP(C0,  OUTPUT_HIGH);	 	  /*BT_UART_RTS#*/
	GPIO_SETUP(C2,  OUTPUT_LOW);		  /*GPS_UART_TXD*/
	GPIO_SETUP(C3,  INPUT_PULL_DOWN);		  /*GPS_UART_RXD*/
	GPIO_SETUP(C6,  OUTPUT_LOW);          /*AP2BB_SLAVE_WAKEUP*/
	GPIO_SETUP(C7,  INPUT_NO_PULL);          /*AP2BB_SLAVE_WAKEUP*/

	GPIO_SETUP(H0,  OUTPUT_LOW);		  /*LCM_BL_PWM*/
	//GPIO_SETUP(H5,  INPUT_PULL_UP);		  /*CAPSENSE_INT*/


	GPIO_SETUP(J5,  INPUT_PULL_DOWN);	  /*GPS_UART_CTS*/
	GPIO_SETUP(J6,  OUTPUT_LOW);	      /*GPS_UART_RTS*/

	GPIO_SETUP(N6,  INPUT_PULL_DOWN);		  /*LCD_ID0*/


	GPIO_SETUP(O5,  OUTPUT_LOW);		  /*BB2AP_FATAL_INT*/


	GPIO_SETUP(Q1,  INPUT_PULL_DOWN);		  /*MB_ID0*/

	GPIO_SETUP(Q5,  OUTPUT_LOW);		  /*BB_KEY1*/

	GPIO_SETUP(R0,  INPUT_PULL_UP);		  /*GPIO_1V8_1WIRE*/
	GPIO_SETUP(R1,  OUTPUT_LOW);		  /*RGB_MIPI_RESET#*/

	GPIO_SETUP(R5,  INPUT_PULL_DOWN);		  /*MB_ID1*/
	GPIO_SETUP(R7,  OUTPUT_LOW);		  /*GPS_EN*/


	GPIO_SETUP(T5,  OUTPUT_LOW);		  /*TP_I2C_SCL*/
	GPIO_SETUP(T6,  OUTPUT_LOW);		  /*TP_I2C_SDA*/

	GPIO_SETUP(U3,  OUTPUT_LOW);  	 	  /*LCM_BL_EN*/

	GPIO_SETUP(V7,  INPUT_PULL_DOWN);		  /*LCM_TE*/

	GPIO_SETUP(W0,  OUTPUT_LOW);		  /*AP2BB_PWRON*/
	GPIO_SETUP(W1,  INPUT_PULL_DOWN);		  /*LCD_ID1*/

	GPIO_SETUP(W6,  OUTPUT_LOW);		  /*BT_UART_TX*/
	GPIO_SETUP(W7,  INPUT_PULL_DOWN);		  /*BT_UART_RX*/


	GPIO_SETUP(BB6,  OUTPUT_LOW);		  /*BB_RESET_STATUS*/

}
void quo_xc_no_owner_gpio_suspend(void)
{
//	GPIO_SETUP(A1,  INPUT_PULL_UP);       /*BT_UART_CTS#*/
//
//	GPIO_SETUP(C0,  OUTPUT_HIGH);	 	  /*BT_UART_RTS#*/
//	GPIO_SETUP(C2,  OUTPUT_LOW);		  /*GPS_UART_TXD*/
//	GPIO_SETUP(C3,  INPUT_PULL_DOWN);		  /*GPS_UART_RXD*/
//	GPIO_SETUP(C6,  OUTPUT_LOW);          /*AP2BB_SLAVE_WAKEUP*/
//	GPIO_SETUP(C7,  INPUT_NO_PULL);          /*1-WIRE_INT*/
//
//	GPIO_SETUP(G6,  INPUT_NO_PULL);          /*RAM_CODE_2*/
//	GPIO_SETUP(G7,  INPUT_NO_PULL);          /*RAM_CODE_3*/
//
//	GPIO_SETUP(J5,  INPUT_PULL_DOWN);	  /*GPS_UART_CTS*/
//	GPIO_SETUP(J6,  OUTPUT_LOW);	      /*GPS_UART_RTS*/
//
//
//	GPIO_SETUP(O5,  OUTPUT_LOW);		  /*reserved*/
//
//
//	GPIO_SETUP(Q1,  INPUT_PULL_DOWN);		  /*MB_ID0*/
//
//	GPIO_SETUP(Q5,  INPUT_PULL_DOWN);		  /*REGION_ID*/
//
//	GPIO_SETUP(R0,  INPUT_PULL_UP);		  /*GPIO_1V8_1WIRE*/
//	GPIO_SETUP(R1,  OUTPUT_LOW);		  /*reserved#*/
//
//	GPIO_SETUP(R5,  INPUT_PULL_DOWN);		  /*MB_ID1*/
//	GPIO_SETUP(R7,  OUTPUT_LOW);		  /*GPS_EN*/
//
//
//	GPIO_SETUP(T5,  OUTPUT_LOW);		  /*TP_I2C_SCL*/
//	GPIO_SETUP(T6,  OUTPUT_LOW);		  /*TP_I2C_SDA*/
//
//	GPIO_SETUP(W0,  OUTPUT_LOW);		  /*AP2BB_PWRON*/
//
//	GPIO_SETUP(W6,  OUTPUT_LOW);		  /*BT_UART_TX*/
//	GPIO_SETUP(W7,  INPUT_PULL_DOWN);		  /*BT_UART_RX*/
//
//
//	GPIO_SETUP(BB6,  OUTPUT_LOW);		  /*BB_RESET_STATUS*/

}

void quo_xd_no_owner_gpio_suspend(void)
{
	DEBUG_ENTRY();
	GPIO_SETUP(A1,  INPUT_PULL_UP);       /*BT_UART_CTS#*/

	GPIO_SETUP(C0,  OUTPUT_HIGH);	 	  /*BT_UART_RTS#*/
	GPIO_SETUP(C2,  OUTPUT_LOW);		  /*GPS_UART_TXD*/
	GPIO_SETUP(C3,  INPUT_PULL_DOWN);		  /*GPS_UART_RXD*/
	GPIO_SETUP(C6,  OUTPUT_LOW);          /*AP2BB_SLAVE_WAKEUP*/
	GPIO_SETUP(C7,  INPUT_NO_PULL);          /*1-WIRE_INT*/

	GPIO_SETUP(G6,  INPUT_NO_PULL);          /*RAM_CODE_2*/
	GPIO_SETUP(G7,  INPUT_NO_PULL);          /*RAM_CODE_3*/
//	GPIO_SETUP(H5,  INPUT_PULL_UP);		  /*CAPSENSE_INT*/


	GPIO_SETUP(J5,  INPUT_PULL_DOWN);	  /*GPS_UART_CTS*/
	GPIO_SETUP(J6,  OUTPUT_LOW);	      /*GPS_UART_RTS*/

//	GPIO_SETUP(N6,  INPUT_PULL_DOWN);		  /*LCD_ID0*/


	GPIO_SETUP(O5,  OUTPUT_LOW);		  /*reserved*/


	GPIO_SETUP(Q1,  INPUT_PULL_DOWN);		  /*MB_ID0*/

	GPIO_SETUP(Q5,  INPUT_PULL_DOWN);		  /*REGION_ID*/

	GPIO_SETUP(R0,  INPUT_PULL_UP);		  /*GPIO_1V8_1WIRE*/
	GPIO_SETUP(R1,  OUTPUT_LOW);		  /*reserved#*/

	GPIO_SETUP(R5,  INPUT_PULL_DOWN);		  /*MB_ID1*/
	GPIO_SETUP(R7,  OUTPUT_LOW);		  /*GPS_EN*/


	GPIO_SETUP(T5,  OUTPUT_LOW);		  /*TP_I2C_SCL*/
	GPIO_SETUP(T6,  OUTPUT_LOW);		  /*TP_I2C_SDA*/

//	GPIO_SETUP(U3,  OUTPUT_LOW);  	 	  /*LCM_BL_EN*/

//	GPIO_SETUP(V7,  INPUT_PULL_DOWN);		  /*LCM_TE*/

	GPIO_SETUP(W0,  OUTPUT_LOW);		  /*AP2BB_PWRON*/
//	GPIO_SETUP(W1,  INPUT_PULL_DOWN);		  /*LCD_ID1*/

	GPIO_SETUP(W6,  OUTPUT_LOW);		  /*BT_UART_TX*/
	GPIO_SETUP(W7,  INPUT_PULL_DOWN);		  /*BT_UART_RX*/


	GPIO_SETUP(BB6,  OUTPUT_LOW);		  /*BB_RESET_STATUS*/

}

void ble_xa_unused_gpio_suspend(void)
{
	DEBUG_ENTRY();
	GPIO_SETUP(A0, OUTPUT_LOW);
	GPIO_SETUP(D0, OUTPUT_LOW);
	GPIO_SETUP(D1, OUTPUT_LOW);
	GPIO_SETUP(D2, OUTPUT_LOW);
	GPIO_SETUP(D3, OUTPUT_LOW);
	GPIO_SETUP(D4, OUTPUT_LOW);
	GPIO_SETUP(E3, OUTPUT_LOW);
	GPIO_SETUP(E4, OUTPUT_LOW);
	GPIO_SETUP(F0, OUTPUT_LOW);
	GPIO_SETUP(F2, OUTPUT_LOW);
	GPIO_SETUP(F4, OUTPUT_LOW);
	GPIO_SETUP(F5, OUTPUT_LOW);
	GPIO_SETUP(H0, OUTPUT_LOW);
	GPIO_SETUP(H1, OUTPUT_LOW);
	GPIO_SETUP(H2, OUTPUT_LOW);
	GPIO_SETUP(H3, OUTPUT_LOW);
	GPIO_SETUP(H4, OUTPUT_LOW);
	GPIO_SETUP(H5, OUTPUT_LOW);
	GPIO_SETUP(H6, OUTPUT_LOW);
	GPIO_SETUP(H7, OUTPUT_LOW);
	GPIO_SETUP(I2, OUTPUT_LOW);
	GPIO_SETUP(I3, OUTPUT_LOW);
	GPIO_SETUP(I4, OUTPUT_LOW);
	GPIO_SETUP(I7, OUTPUT_LOW);
	GPIO_SETUP(J3, OUTPUT_LOW);
	GPIO_SETUP(J4, OUTPUT_LOW);
	GPIO_SETUP(J6, OUTPUT_LOW);
	GPIO_SETUP(K0, INPUT_NO_PULL);
	GPIO_SETUP(K1, INPUT_NO_PULL);
	GPIO_SETUP(K3, OUTPUT_LOW);
	GPIO_SETUP(K4, OUTPUT_LOW);
	GPIO_SETUP(K5, OUTPUT_LOW);
	GPIO_SETUP(K6, OUTPUT_LOW);
	GPIO_SETUP(M3, OUTPUT_LOW);
	GPIO_SETUP(M5, OUTPUT_LOW);
	GPIO_SETUP(M6, OUTPUT_LOW);
	GPIO_SETUP(N4, OUTPUT_LOW);
	GPIO_SETUP(N5, OUTPUT_LOW);
	GPIO_SETUP(N7, OUTPUT_LOW);
	GPIO_SETUP(O0, OUTPUT_LOW);
	GPIO_SETUP(O3, OUTPUT_LOW);
	GPIO_SETUP(O6, OUTPUT_LOW);
	GPIO_SETUP(O7, OUTPUT_LOW);
	GPIO_SETUP(Q0, OUTPUT_LOW);
	GPIO_SETUP(Q1, OUTPUT_LOW);
	GPIO_SETUP(Q2, OUTPUT_LOW);
	GPIO_SETUP(Q3, OUTPUT_LOW);
	GPIO_SETUP(Q4, OUTPUT_LOW);
	GPIO_SETUP(Q5, OUTPUT_LOW);
	GPIO_SETUP(Q6, OUTPUT_LOW);
	GPIO_SETUP(Q7, OUTPUT_LOW);
	GPIO_SETUP(R0, OUTPUT_LOW);
	GPIO_SETUP(R2, OUTPUT_LOW);
	GPIO_SETUP(R3, OUTPUT_LOW);
	GPIO_SETUP(R4, OUTPUT_LOW);
	GPIO_SETUP(R5, OUTPUT_LOW);
	GPIO_SETUP(S1, OUTPUT_LOW);
	GPIO_SETUP(U1, OUTPUT_LOW);
	GPIO_SETUP(U2, OUTPUT_LOW);
	GPIO_SETUP(U3, OUTPUT_LOW);
	GPIO_SETUP(V3, OUTPUT_LOW);
	GPIO_SETUP(V4, OUTPUT_LOW);
	GPIO_SETUP(V5, OUTPUT_LOW);
	GPIO_SETUP(V7, OUTPUT_LOW);
	GPIO_SETUP(X4, OUTPUT_LOW);
	GPIO_SETUP(X6, OUTPUT_LOW);
	GPIO_SETUP(Y0, OUTPUT_LOW);
	GPIO_SETUP(Y4, OUTPUT_LOW);
	GPIO_SETUP(Y5, OUTPUT_LOW);
	GPIO_SETUP(Y6, OUTPUT_LOW);
	GPIO_SETUP(Y7, OUTPUT_LOW);
	GPIO_SETUP(Z0, OUTPUT_LOW);
	GPIO_SETUP(Z1, OUTPUT_LOW);
	GPIO_SETUP(Z3, OUTPUT_LOW);
	GPIO_SETUP(Z4, OUTPUT_LOW);
	GPIO_SETUP(Z5, INPUT_NO_PULL);
	GPIO_SETUP(BB6, OUTPUT_LOW);
	GPIO_SETUP(CC5, OUTPUT_LOW);
	GPIO_SETUP(EE0, OUTPUT_LOW);
	GPIO_SETUP(EE1, OUTPUT_LOW);
	GPIO_SETUP(EE3, OUTPUT_LOW);
	GPIO_SETUP(G0, INPUT_NO_PULL);
	GPIO_SETUP(G1, INPUT_NO_PULL);
	GPIO_SETUP(G2, INPUT_NO_PULL);
	GPIO_SETUP(G3, INPUT_NO_PULL);
	GPIO_SETUP(G4, INPUT_NO_PULL);
	GPIO_SETUP(G5, INPUT_NO_PULL);
	GPIO_SETUP(G6, INPUT_NO_PULL);
	GPIO_SETUP(G7, INPUT_NO_PULL);

	GPIO_SETUP(J1, INPUT_PULL_DOWN);
	GPIO_SETUP(V6, INPUT_PULL_UP);
	GPIO_SETUP(I0, INPUT_NO_PULL);
	GPIO_SETUP(I1, INPUT_NO_PULL);
	GPIO_SETUP(P4, OUTPUT_LOW);	//BT
	GPIO_SETUP(P5, OUTPUT_LOW);	//BT
	GPIO_SETUP(P6, OUTPUT_LOW);	//BT
	GPIO_SETUP(P7, OUTPUT_LOW);	//BT
}

void enr_u_xc_unused_gpio_init(void)
{
	GPIO_SETUP(D3, OUTPUT_LOW);
	GPIO_SETUP(D4, OUTPUT_LOW);
	GPIO_SETUP(F0, OUTPUT_LOW);
	GPIO_SETUP(F2, OUTPUT_LOW);
	GPIO_SETUP(J3, OUTPUT_LOW);
	GPIO_SETUP(P7, OUTPUT_LOW);
	GPIO_SETUP(U1, OUTPUT_LOW);
	GPIO_SETUP(U2, OUTPUT_LOW);
	GPIO_SETUP(U5, OUTPUT_LOW);
}

void enr_u_xd_unused_gpio_init(void)
{
	GPIO_SETUP(D3, OUTPUT_LOW);
	GPIO_SETUP(D4, OUTPUT_LOW);
	GPIO_SETUP(F0, OUTPUT_LOW);
	GPIO_SETUP(F2, OUTPUT_LOW);
	GPIO_SETUP(J3, OUTPUT_LOW);
	GPIO_SETUP(P7, OUTPUT_LOW);
	GPIO_SETUP(U1, OUTPUT_LOW);
	GPIO_SETUP(U2, OUTPUT_LOW);
	GPIO_SETUP(U5, OUTPUT_LOW);
}
void enr_u_xe_unused_gpio_init(void)
{
	GPIO_SETUP(D3, OUTPUT_LOW);
	GPIO_SETUP(D4, OUTPUT_LOW);
	GPIO_SETUP(F0, OUTPUT_LOW);
	GPIO_SETUP(F2, OUTPUT_LOW);
	GPIO_SETUP(J3, OUTPUT_LOW);
	GPIO_SETUP(P7, OUTPUT_LOW);
	GPIO_SETUP(U1, OUTPUT_LOW);
	GPIO_SETUP(U2, OUTPUT_LOW);
	GPIO_SETUP(U5, OUTPUT_LOW);
}
void enr_td_xc_unused_gpio_init(void)
{
	GPIO_SETUP(E1, OUTPUT_LOW);
	GPIO_SETUP(N1, OUTPUT_LOW);
}

void enr_xc_unused_gpio_init(void)
{
	DEBUG_ENTRY();
	GPIO_SETUP(A0, OUTPUT_LOW);
	GPIO_SETUP(D0, OUTPUT_LOW);
	GPIO_SETUP(D1, OUTPUT_LOW);
	GPIO_SETUP(D5, OUTPUT_LOW);
	GPIO_SETUP(D6, OUTPUT_LOW);
	GPIO_SETUP(D7, OUTPUT_LOW);

	GPIO_SETUP(H1, OUTPUT_LOW);
	GPIO_SETUP(H2, OUTPUT_LOW);
	GPIO_SETUP(H4, OUTPUT_LOW);
	GPIO_SETUP(H5, OUTPUT_LOW);
	GPIO_SETUP(H6, OUTPUT_LOW);
	GPIO_SETUP(H7, OUTPUT_LOW);
	GPIO_SETUP(I2, OUTPUT_LOW);
	GPIO_SETUP(I3, OUTPUT_LOW);
	GPIO_SETUP(I4, OUTPUT_LOW);
	GPIO_SETUP(I7, OUTPUT_LOW);

	GPIO_SETUP(J4, OUTPUT_LOW);
	GPIO_SETUP(K3, OUTPUT_LOW);
	GPIO_SETUP(K4, OUTPUT_LOW);
	GPIO_SETUP(K5, OUTPUT_LOW);
	GPIO_SETUP(K6, OUTPUT_LOW);
	GPIO_SETUP(L0, OUTPUT_LOW);
	GPIO_SETUP(L1, OUTPUT_LOW);
	GPIO_SETUP(L2, OUTPUT_LOW);
	GPIO_SETUP(L3, OUTPUT_LOW);
	GPIO_SETUP(L4, OUTPUT_LOW);
	GPIO_SETUP(L5, OUTPUT_LOW);
	GPIO_SETUP(L6, OUTPUT_LOW);
	GPIO_SETUP(L7, OUTPUT_LOW);
	GPIO_SETUP(M3, OUTPUT_LOW);
	GPIO_SETUP(N4, OUTPUT_LOW);
	GPIO_SETUP(O0, OUTPUT_LOW);
	GPIO_SETUP(O3, OUTPUT_LOW);
	GPIO_SETUP(O6, OUTPUT_LOW);
	GPIO_SETUP(O7, OUTPUT_LOW);
	GPIO_SETUP(P0, OUTPUT_LOW);
	GPIO_SETUP(P1, OUTPUT_LOW);
	GPIO_SETUP(P2, OUTPUT_LOW);
	GPIO_SETUP(P3, OUTPUT_LOW);
	GPIO_SETUP(P4, OUTPUT_LOW);
	GPIO_SETUP(P5, OUTPUT_LOW);
	GPIO_SETUP(P6, OUTPUT_LOW);

	GPIO_SETUP(Q0, OUTPUT_LOW);
	GPIO_SETUP(Q1, OUTPUT_LOW);
	GPIO_SETUP(Q2, OUTPUT_LOW);
	GPIO_SETUP(Q3, OUTPUT_LOW);
	GPIO_SETUP(Q4, OUTPUT_LOW);
	GPIO_SETUP(Q5, OUTPUT_LOW);
	GPIO_SETUP(Q6, OUTPUT_LOW);
	GPIO_SETUP(Q7, OUTPUT_LOW);

	GPIO_SETUP(S1, OUTPUT_LOW);
	GPIO_SETUP(S3, OUTPUT_LOW);
	GPIO_SETUP(S4, OUTPUT_LOW);
	GPIO_SETUP(S5, OUTPUT_LOW);
	GPIO_SETUP(S6, OUTPUT_LOW);
	GPIO_SETUP(S7, OUTPUT_LOW);

	GPIO_SETUP(T0, OUTPUT_LOW);
	GPIO_SETUP(T1, OUTPUT_LOW);
	GPIO_SETUP(T2, OUTPUT_LOW);
	GPIO_SETUP(T3, OUTPUT_LOW);
	GPIO_SETUP(T4, OUTPUT_LOW);


	GPIO_SETUP(V3, OUTPUT_LOW);
	GPIO_SETUP(V7, OUTPUT_LOW);
	GPIO_SETUP(X4, OUTPUT_LOW);
	GPIO_SETUP(X6, OUTPUT_LOW);
	GPIO_SETUP(Y7, OUTPUT_LOW);
	GPIO_SETUP(Z1, OUTPUT_LOW);
	GPIO_SETUP(Z3, OUTPUT_LOW);
	GPIO_SETUP(Z4, OUTPUT_LOW);
	GPIO_SETUP(BB0, OUTPUT_LOW);
	GPIO_SETUP(BB7, OUTPUT_LOW);
	GPIO_SETUP(CC6, OUTPUT_LOW);
	GPIO_SETUP(CC7, OUTPUT_LOW);
	GPIO_SETUP(DD0, OUTPUT_LOW);
	GPIO_SETUP(DD1, OUTPUT_LOW);
	GPIO_SETUP(DD2, OUTPUT_LOW);
	GPIO_SETUP(DD3, OUTPUT_LOW);
	GPIO_SETUP(DD4, OUTPUT_LOW);
	GPIO_SETUP(DD5, OUTPUT_LOW);
	GPIO_SETUP(DD6, OUTPUT_LOW);
	GPIO_SETUP(DD7, OUTPUT_LOW);
	GPIO_SETUP(EE0, OUTPUT_LOW);
	GPIO_SETUP(EE2, OUTPUT_LOW);
	GPIO_SETUP(EE3, OUTPUT_LOW);
}
void enr_xd_unused_gpio_init(void)
{
	DEBUG_ENTRY();
	GPIO_SETUP(A0, OUTPUT_LOW);
	GPIO_SETUP(D0, OUTPUT_LOW);
	GPIO_SETUP(D1, OUTPUT_LOW);
	GPIO_SETUP(D5, OUTPUT_LOW);
	GPIO_SETUP(D6, OUTPUT_LOW);
	GPIO_SETUP(D7, OUTPUT_LOW);

	GPIO_SETUP(H1, OUTPUT_LOW);
	GPIO_SETUP(H2, OUTPUT_LOW);
	GPIO_SETUP(H4, OUTPUT_LOW);
	GPIO_SETUP(H5, OUTPUT_LOW);
	GPIO_SETUP(H6, OUTPUT_LOW);
	GPIO_SETUP(H7, OUTPUT_LOW);
	GPIO_SETUP(I2, OUTPUT_LOW);
	GPIO_SETUP(I3, OUTPUT_LOW);
	GPIO_SETUP(I4, OUTPUT_LOW);
	GPIO_SETUP(I7, OUTPUT_LOW);

	GPIO_SETUP(J4, OUTPUT_LOW);
	GPIO_SETUP(K3, OUTPUT_LOW);
	GPIO_SETUP(K4, OUTPUT_LOW);
	GPIO_SETUP(K5, OUTPUT_LOW);
	GPIO_SETUP(K6, OUTPUT_LOW);
	GPIO_SETUP(L0, OUTPUT_LOW);
	GPIO_SETUP(L1, OUTPUT_LOW);
	GPIO_SETUP(L2, OUTPUT_LOW);
	GPIO_SETUP(L3, OUTPUT_LOW);
	GPIO_SETUP(L4, OUTPUT_LOW);
	GPIO_SETUP(L5, OUTPUT_LOW);
	GPIO_SETUP(L6, OUTPUT_LOW);
	GPIO_SETUP(L7, OUTPUT_LOW);
	GPIO_SETUP(N4, OUTPUT_LOW);
	GPIO_SETUP(O0, OUTPUT_LOW);
	GPIO_SETUP(O3, OUTPUT_LOW);
	GPIO_SETUP(O6, OUTPUT_LOW);
	GPIO_SETUP(O7, OUTPUT_LOW);
	GPIO_SETUP(P0, OUTPUT_LOW);
	GPIO_SETUP(P1, OUTPUT_LOW);
	GPIO_SETUP(P2, OUTPUT_LOW);
	GPIO_SETUP(P3, OUTPUT_LOW);
	GPIO_SETUP(P4, OUTPUT_LOW);
	GPIO_SETUP(P5, OUTPUT_LOW);

	GPIO_SETUP(Q0, OUTPUT_LOW);
	GPIO_SETUP(Q1, OUTPUT_LOW);
	GPIO_SETUP(Q2, OUTPUT_LOW);
	GPIO_SETUP(Q3, OUTPUT_LOW);
	GPIO_SETUP(Q4, OUTPUT_LOW);
	GPIO_SETUP(Q5, OUTPUT_LOW);
	GPIO_SETUP(Q6, OUTPUT_LOW);
	GPIO_SETUP(Q7, OUTPUT_LOW);

	GPIO_SETUP(S1, OUTPUT_LOW);
	GPIO_SETUP(S3, OUTPUT_LOW);
	GPIO_SETUP(S4, OUTPUT_LOW);
	GPIO_SETUP(S5, OUTPUT_LOW);
	GPIO_SETUP(S6, OUTPUT_LOW);
	GPIO_SETUP(S7, OUTPUT_LOW);

	GPIO_SETUP(T0, OUTPUT_LOW);
	GPIO_SETUP(T1, OUTPUT_LOW);
	GPIO_SETUP(T2, OUTPUT_LOW);
	GPIO_SETUP(T3, OUTPUT_LOW);
	GPIO_SETUP(T4, OUTPUT_LOW);


	GPIO_SETUP(V3, OUTPUT_LOW);
	GPIO_SETUP(V7, OUTPUT_LOW);
	GPIO_SETUP(X4, OUTPUT_LOW);
	GPIO_SETUP(X6, OUTPUT_LOW);
	GPIO_SETUP(Y7, OUTPUT_LOW);
	GPIO_SETUP(Z1, OUTPUT_LOW);
	GPIO_SETUP(Z3, OUTPUT_LOW);
	GPIO_SETUP(Z4, OUTPUT_LOW);
	GPIO_SETUP(BB0, OUTPUT_LOW);
	GPIO_SETUP(BB7, OUTPUT_LOW);
	GPIO_SETUP(CC6, OUTPUT_LOW);
	GPIO_SETUP(CC7, OUTPUT_LOW);
	GPIO_SETUP(DD0, OUTPUT_LOW);
	GPIO_SETUP(DD1, OUTPUT_LOW);
	GPIO_SETUP(DD2, OUTPUT_LOW);
	GPIO_SETUP(DD3, OUTPUT_LOW);
	GPIO_SETUP(DD4, OUTPUT_LOW);
	GPIO_SETUP(DD5, OUTPUT_LOW);
	GPIO_SETUP(DD6, OUTPUT_LOW);
	GPIO_SETUP(DD7, OUTPUT_LOW);
	GPIO_SETUP(EE0, OUTPUT_LOW);
	GPIO_SETUP(EE2, OUTPUT_LOW);
	GPIO_SETUP(EE3, OUTPUT_LOW);
}

void enr_xe_unused_gpio_init(void)
{
	DEBUG_ENTRY();
	GPIO_SETUP(A0, OUTPUT_LOW);
	GPIO_SETUP(D0, OUTPUT_LOW);
	GPIO_SETUP(D1, OUTPUT_LOW);
	GPIO_SETUP(D5, OUTPUT_LOW);
	GPIO_SETUP(D6, OUTPUT_LOW);
	GPIO_SETUP(D7, OUTPUT_LOW);

	GPIO_SETUP(H1, OUTPUT_LOW);
	GPIO_SETUP(H2, OUTPUT_LOW);
	GPIO_SETUP(H4, OUTPUT_LOW);
	GPIO_SETUP(H5, OUTPUT_LOW);
	GPIO_SETUP(H6, OUTPUT_LOW);
	GPIO_SETUP(H7, OUTPUT_LOW);
	GPIO_SETUP(I2, OUTPUT_LOW);
	GPIO_SETUP(I3, OUTPUT_LOW);
	GPIO_SETUP(I4, OUTPUT_LOW);
	GPIO_SETUP(I7, OUTPUT_LOW);

	GPIO_SETUP(J4, OUTPUT_LOW);
	GPIO_SETUP(K3, OUTPUT_LOW);
	GPIO_SETUP(K4, OUTPUT_LOW);
	GPIO_SETUP(K5, OUTPUT_LOW);
	GPIO_SETUP(K6, OUTPUT_LOW);
	GPIO_SETUP(L0, OUTPUT_LOW);
	GPIO_SETUP(L1, OUTPUT_LOW);
	GPIO_SETUP(L2, OUTPUT_LOW);
	GPIO_SETUP(L3, OUTPUT_LOW);
	GPIO_SETUP(L4, OUTPUT_LOW);
	GPIO_SETUP(L5, OUTPUT_LOW);
	GPIO_SETUP(L6, OUTPUT_LOW);
	GPIO_SETUP(L7, OUTPUT_LOW);
	GPIO_SETUP(N4, OUTPUT_LOW);
	GPIO_SETUP(O0, OUTPUT_LOW);
	GPIO_SETUP(O3, OUTPUT_LOW);
	GPIO_SETUP(O6, OUTPUT_LOW);
	GPIO_SETUP(O7, OUTPUT_LOW);
	GPIO_SETUP(P0, OUTPUT_LOW);
	GPIO_SETUP(P1, OUTPUT_LOW);
	GPIO_SETUP(P2, OUTPUT_LOW);
	GPIO_SETUP(P3, OUTPUT_LOW);
	GPIO_SETUP(P4, OUTPUT_LOW);
	GPIO_SETUP(P5, OUTPUT_LOW);

	GPIO_SETUP(Q0, OUTPUT_LOW);
	GPIO_SETUP(Q1, OUTPUT_LOW);
	GPIO_SETUP(Q2, OUTPUT_LOW);
	GPIO_SETUP(Q3, OUTPUT_LOW);
	GPIO_SETUP(Q4, OUTPUT_LOW);
	GPIO_SETUP(Q5, OUTPUT_LOW);
	GPIO_SETUP(Q6, OUTPUT_LOW);
	GPIO_SETUP(Q7, OUTPUT_LOW);

	GPIO_SETUP(S1, OUTPUT_LOW);
	GPIO_SETUP(S3, OUTPUT_LOW);
	GPIO_SETUP(S4, OUTPUT_LOW);
	GPIO_SETUP(S5, OUTPUT_LOW);
	GPIO_SETUP(S6, OUTPUT_LOW);
	GPIO_SETUP(S7, OUTPUT_LOW);

	GPIO_SETUP(R5, OUTPUT_LOW);

	GPIO_SETUP(T0, OUTPUT_LOW);
	GPIO_SETUP(T1, OUTPUT_LOW);
	GPIO_SETUP(T2, OUTPUT_LOW);
	GPIO_SETUP(T3, OUTPUT_LOW);
	GPIO_SETUP(T4, OUTPUT_LOW);


	GPIO_SETUP(V3, OUTPUT_LOW);
	GPIO_SETUP(V7, OUTPUT_LOW);
	GPIO_SETUP(X4, OUTPUT_LOW);
	GPIO_SETUP(X6, OUTPUT_LOW);
	GPIO_SETUP(Y7, OUTPUT_LOW);
	GPIO_SETUP(Z1, OUTPUT_LOW);
	GPIO_SETUP(Z3, OUTPUT_LOW);
	GPIO_SETUP(Z4, OUTPUT_LOW);
	GPIO_SETUP(BB0, OUTPUT_LOW);
	GPIO_SETUP(BB7, OUTPUT_LOW);
	GPIO_SETUP(CC6, OUTPUT_LOW);
	GPIO_SETUP(CC7, OUTPUT_LOW);
	GPIO_SETUP(DD0, OUTPUT_LOW);
	GPIO_SETUP(DD1, OUTPUT_LOW);
	GPIO_SETUP(DD2, OUTPUT_LOW);
	GPIO_SETUP(DD3, OUTPUT_LOW);
	GPIO_SETUP(DD4, OUTPUT_LOW);
	GPIO_SETUP(DD5, OUTPUT_LOW);
	GPIO_SETUP(DD6, OUTPUT_LOW);
	GPIO_SETUP(DD7, OUTPUT_LOW);
	GPIO_SETUP(EE0, OUTPUT_LOW);
	GPIO_SETUP(EE2, OUTPUT_LOW);
	GPIO_SETUP(EE3, OUTPUT_LOW);
}
#endif

void enr_td_xc_no_owner_gpio_init(void)
{
	if (is_modem_rework_phase()) {
		pr_info("[MODEM REWORK] skip enr_td_xc_no_owner_gpio_init\n");
		return;
	}
	enr_xc_unused_gpio_init();
	enr_td_xc_unused_gpio_init();
	enr_xc_no_owner_gpio_init();
}

void enr_u_xc_no_owner_gpio_init(void)
{
	enr_xc_unused_gpio_init();
	enr_u_xc_unused_gpio_init();
	enr_xc_no_owner_gpio_init();
}
void enr_u_xd_no_owner_gpio_init(void)
{
	enr_xd_unused_gpio_init();
	enr_u_xd_unused_gpio_init();
	enr_xd_no_owner_gpio_init();
}

void enr_u_xe_no_owner_gpio_init(void)
{
	enr_xe_unused_gpio_init();
	enr_u_xe_unused_gpio_init();
	enr_xe_no_owner_gpio_init();
}

static struct gpio_callbacks* gpio_basic_callbacks = {NULL};

void register_gpio_basic_callbacks(struct gpio_callbacks* callbacks)
{
	gpio_basic_callbacks = callbacks;
}

// TODO should be called after suspend function of gpio and pinmux
void gpio_basic_during_suspend(void)
{
	if (gpio_basic_callbacks && gpio_basic_callbacks->during_suspend)
		gpio_basic_callbacks->during_suspend();
}

static int gpio_basic_pm_notify(struct notifier_block *nb,
			    unsigned long event, void *data)
{
	switch (event) {
	case PM_SUSPEND_PREPARE:
		if (gpio_basic_callbacks && gpio_basic_callbacks->resume)
			gpio_basic_callbacks->suspend();
		break;
	case PM_POST_SUSPEND:
		if (gpio_basic_callbacks && gpio_basic_callbacks->resume)
			gpio_basic_callbacks->resume();
		break;
	}

	return NOTIFY_OK;
};

static struct notifier_block gpio_basic_pm_nb = {
	.notifier_call = gpio_basic_pm_notify,
};

static int __init gpio_basic_init(void)
{
	if (gpio_basic_callbacks && gpio_basic_callbacks->init)
		gpio_basic_callbacks->init();

	register_pm_notifier(&gpio_basic_pm_nb);
	return 0;
}
late_initcall(gpio_basic_init);
