#ifndef __PANEL_ID_H
#define __PANEL_ID_H

/* BIT0 - BIT15 : panel id */
/* BIT16 - BIT18 : backlight interface */
/* BIT19- BIT21 : display interface */
/* BIT22- BIT24 : color depth */
/* BIT25- BIT27 : lcm revision */
/* BIT28- BIT31 : reserved */

#define BL_SHIFT	16
#define BL_MASK		(0x7 << BL_SHIFT)

#define BL_SPI		(0 << BL_SHIFT)
#define BL_MDDI		(1 << BL_SHIFT)
#define BL_I2C		(2 << BL_SHIFT)
#define BL_UP		(3 << BL_SHIFT)
#define BL_MIPI		(4 << BL_SHIFT)
#define BL_PMIC		(5 << BL_SHIFT)
#define BL_CPU		(6 << BL_SHIFT)

#define IF_SHIFT	19
#define IF_MASK		(0x7 << IF_SHIFT)

#define IF_LCDC		(0 << IF_SHIFT)
#define IF_MDDI		(1 << IF_SHIFT)
#define IF_MIPI		(2 << IF_SHIFT)

#define DEPTH_SHIFT	22
#define DEPTH_MASK	(0x7 << DEPTH_SHIFT)

#define DEPTH_RGB565	(0 << DEPTH_SHIFT)
#define DEPTH_RGB666	(1 << DEPTH_SHIFT)
#define DEPTH_RGB888	(2 << DEPTH_SHIFT)


#define REV_SHIFT	25
#define REV_MASK	(0x7 << REV_SHIFT)

#define REV_0		(0 << REV_SHIFT)
#define REV_1		(1 << REV_SHIFT)
#define REV_2		(2 << REV_SHIFT)


#define PANEL_ID_NONE		(0x0)

#define	PANEL_ID_START		0x0F

#define PANEL_ID(pro, ven, ic) PANEL_ID_##pro##_##ven##_##ic

#define PANEL_ID_ENR_SHARP_HX_XA	(0x01 | BL_CPU | IF_MIPI | DEPTH_RGB888 | REV_0)
#define PANEL_ID_ENRTD_SHARP_HX_XA	(0x02 | BL_CPU | IF_MIPI | DEPTH_RGB888 | REV_0)
#define PANEL_ID_ENR_SHARP_NT_C1	(0x03 | BL_MIPI | IF_MIPI | DEPTH_RGB888 | REV_0)
#define PANEL_ID_ENR_SONY_NT_C1		(0x04 | BL_MIPI | IF_MIPI | DEPTH_RGB888 | REV_0)
#define PANEL_ID_ENR_SHARP_HX_C3	(0x05 | BL_MIPI | IF_MIPI | DEPTH_RGB888 | REV_0)
#define PANEL_ID_ENRTD_SHARP_NT_C1	(0x06 | BL_MIPI | IF_MIPI | DEPTH_RGB888 | REV_0)
#define PANEL_ID_ENRTD_SONY_NT_C1	(0x07 | BL_MIPI | IF_MIPI | DEPTH_RGB888 | REV_0)
#define PANEL_ID_ENRTD_SHARP_HX_C3	(0x08 | BL_MIPI | IF_MIPI | DEPTH_RGB888 | REV_0)
#define PANEL_ID_VEX_CHIMEI_TB		(0x09 | BL_CPU	| IF_MIPI | DEPTH_RGB888)
#define PANEL_ID_VEX_LG_TB		(0x0a | BL_CPU	| IF_MIPI | DEPTH_RGB888)
#define PANEL_ID_VEX_CHIMEI_TI		(0x0c | BL_CPU	| IF_LCDC | DEPTH_RGB888)
#define PANEL_ID_VEX_LG_TI		(0x0d | BL_CPU	| IF_LCDC | DEPTH_RGB888)
#define PANEL_ID_VEX_PANA_TB        	(0x0b | BL_CPU  | IF_LCDC | DEPTH_RGB888)
#define PANEL_ID_ENR_SHARP_NT_C2	(0x0e | BL_MIPI | IF_MIPI | DEPTH_RGB888 | REV_1)
#define PANEL_ID_ENR_SONY_NT_C2		(0x0f | BL_MIPI | IF_MIPI | DEPTH_RGB888 | REV_1)
#define PANEL_ID_ENR_SHARP_HX_C4	(0x10 | BL_MIPI | IF_MIPI | DEPTH_RGB888 | REV_1)
#define PANEL_ID_ENRTD_SHARP_NT_C2	(0x11 | BL_MIPI | IF_MIPI | DEPTH_RGB888 | REV_1)
#define PANEL_ID_ENRTD_SONY_NT_C2	(0x12 | BL_MIPI | IF_MIPI | DEPTH_RGB888 | REV_1)
#define PANEL_ID_ENRTD_SHARP_HX_C4	(0x13 | BL_MIPI | IF_MIPI | DEPTH_RGB888 | REV_1)

#define PANEL_ID_ENR_SHARP_NT_C2_9A	(0x14 | BL_MIPI | IF_MIPI | DEPTH_RGB888 | REV_2)
#define PANEL_ID_ENRTD_SHARP_NT_C2_9A	(0x15 | BL_MIPI | IF_MIPI | DEPTH_RGB888 | REV_2)
#define PANEL_ID_ENR_SHARP		(0x16 | BL_MIPI | IF_MIPI | DEPTH_RGB888)
#define PANEL_ID_ENRTD_SHARP		(0x17 | BL_MIPI | IF_MIPI | DEPTH_RGB888)
#define PANEL_ID_ENR_SONY		(0x18 | BL_MIPI | IF_MIPI | DEPTH_RGB888)
#define PANEL_ID_ENRTD_SONY		(0x19 | BL_MIPI | IF_MIPI | DEPTH_RGB888)
#define PANEL_ID_VEX_CHIMEI_TI_3V	(0x2a | BL_CPU	| IF_LCDC | DEPTH_RGB888)
#define PANEL_ID_VEX_LG_TI_3V		(0x2b | BL_CPU	| IF_LCDC | DEPTH_RGB888)
//Example
#if 0
#define PANEL_ID_DOT_SONY_C3		(0x24 | BL_MIPI | IF_MIPI | DEPTH_RGB888 | REV_1)
#define PANEL_ID_SHR_SHARP_NT		(0x26 | BL_MIPI | IF_MIPI | DEPTH_RGB888)
#define PANEL_ID_EXP_SMD			(0x27 | BL_UP | IF_LCDC | DEPTH_RGB888)
#endif
#define	PANEL_ID_END		0xFFFF

#endif	/*__PANEL_ID_H */

